### ISSUE TITLE
Cases non collectées dans les tableaux (Tables - Substitution for variables marked as not collected)

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Eno#1000]
En DDI, chaque réponse d'un tableau est indiquée grâce à la structure : d:QuestionGrid / d:StructuredMixedGridResponseDomain / d:GridResponseDomainInMixed ; au sein de cet élément, il y a un d:xxxDomain qui indique le format de la réponse et d:GridAttachment qui contient uniquement d:CellCoordinatesAsDefined qui correspond aux coordonnées de la réponse.

Pour les cases non collectées, il y a d:QuestionGrid / d:StructuredMixedGridResponseDomain / d:NoDataByDefinition qui contient uniquement le d:CellCoordinatesAsDefined (comme ci-dessus) qui correspond aux coordonnées de la case sans réponse.

Lorsque la case sans collecte de réponse a un libellé, il se trouve dans d:QuestionGrid / d:CellLabel avec r:TypeOfLabel = 'fixedcell' ; l'association entre la case et le CellLabel se fait par d:CellLabel / d:GridAttachment / d:CellCoordinatesAsDefined qui doit être identique à celui de la case où l'on doit rajouter le libellé. Le libellé se trouve dans d:CellLabel / r:Content

Exemple avec une réponse en case 1, une case avec libellé en case 2 et une case sans libellé en case 3 : 
```
         <d:QuestionGrid>
           ...
            <d:StructuredMixedGridResponseDomain>
               <d:GridResponseDomainInMixed>
                  <d:xxxDomain>...</d:xxxDomain>
                  <d:GridAttachment>
                     <d:CellCoordinatesAsDefined>
                        <d:SelectDimension rank="1" rangeMinimum="1" rangeMaximum="1"/>
                     </d:CellCoordinatesAsDefined>
                  </d:GridAttachment>
               </d:GridResponseDomainInMixed>
               <d:NoDataByDefinition>
                  <d:CellCoordinatesAsDefined>
                     <d:SelectDimension rank="1" rangeMinimum="2" rangeMaximum="2"/>
                  </d:CellCoordinatesAsDefined>
               </d:NoDataByDefinition>
               <d:NoDataByDefinition>
                  <d:CellCoordinatesAsDefined>
                     <d:SelectDimension rank="1" rangeMinimum="3" rangeMaximum="3"/>
                  </d:CellCoordinatesAsDefined>
               </d:NoDataByDefinition>
            </d:StructuredMixedGridResponseDomain>
            <d:CellLabel xmlns="">
               <r:Content xml:lang="fr-FR">"Libellé de la case 2, alors que la 3 n'en a pas"</r:Content>
               <r:TypeOfLabel>fixedcell</r:TypeOfLabel>
               <d:GridAttachment>
                  <d:CellCoordinatesAsDefined>
                     <d:SelectDimension rank="1" rangeMinimum="2" rangeMaximum="2"/>
                  </d:CellCoordinatesAsDefined>
               </d:GridAttachment>
            </d:CellLabel>
         </d:QuestionGrid>
```

L'équivalent côté Lunatic, c'est le composant Text (jusqu'ici absent de Lunatic-model ?) contenant en label le Content du DDI.
Très simple, je propose de l'utiliser même pour les cases vides

```
		{
			"componentType": "Table ou RosterForLoop",
                        ...
			"body": [
					{
						"componentType": "Réponse de la première case",
					},
					{
						"componentType": "Text",
						"conditionFilter": { "value": "true", "type": "VTL" },
						"id": "id-text-2",
						"label": {
							"type": "TXT",
							"value": "Libellé de la case 2, alors que la 3 n'en a pas"
						}
					},
					{
						"componentType": "Text",
						"conditionFilter": { "value": "true", "type": "VTL" },
						"id": "id-text-3",
						"label": {
							"type": "TXT",
							"value": ""
						}
					},
				],
		},
```
Les exemples montrent le composant Text avec un id. S'il en faut un, je propose l'identifiant du tableau, suivi des coordonnées de la case (avec un séparateur s'il y a plusieurs dimensions pour éviter d'avoir un doublon entre la case 1-12 et la case 11-2 par exemple).
J'ai aussi un doute sur l'intérêt d'un conditionFilter valant systématiquement "true".

**Comment by nsenave** [comment]
Je vois l'idée derrière les composants de type `"Text"`, mais les libellés à l'intérieur doivent bien être de type `"VTL"` si on veut pouvoir les évaluer dynamiquement non ?

```diff
					{
						"componentType": "Text",
						"conditionFilter": { "value": "true", "type": "VTL" },
						"id": "id-text-2",
						"label": {
-							"type": "TXT",
+							"type": "VTL",
							"value": "Libellé de la case 2, alors que la 3 n'en a pas"
						}
					}
```

(Un label de type `"TXT"` ça serait pour des libellés pour lesquels ont veut une valeur fixe et se passer d'appeler une évaluation VTL, ici on veut simplement afficher l'info au répondant sans qu'il puisse l'éditer à cet endroit-là)

**Comment by romaintailhurat** [comment]
Thanks for this feat!

I'm testing it and found a first problem.

In a fixed table in Pogues, i change the first cell (1,1) to be _non-collected_ and add a reference to a variable, then i get this error message: 

`Unknown error during generation: Cannot invoke "fr.insee.eno.core.model.variable.Variable.getCollectionType()" because "variable" is null`

The same happens if instead of a variable i just use an arbitrary VTL expressions (like a simple string).

**Comment by nsenave** [comment]
@romaintailhurat The problem is earlier in Pogues side: when a cell is checked as "not collecte", the variable gets removed, yet references in VTL expressions that use the variable remains. 

Yet I improved the exception management if the case happens: https://github.com/InseeFr/Eno/pull/1041/commits/6fba68113151172e68a89ae8b94795f7ac89c511
