### ISSUE TITLE
Affichage de 2147483647 dans la description des InputNumber

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#1022]
La description proposée au dessus des InputNumber affiche l'unité et les bornes min et max.
Si la borne max spécifiée dans Pogues dépasse 2^31, l'affichage est dégradé (affiche le chiffre 2147483647 qui correspond au nombre max de l'objet java `int`].

Or côté enquêtes entreprises, quand la collecte est en euros, on peut dépasser ce montant à juste titre.

Correction  proposée : si borne max > 2 000 000 000 OU borne min < - 2 000 000 000, n'afficher que l'unité si elle existe. Sinon ne rien afficher.

Proposition de Description :
"Format attendu : un nombre " || (si unité non vide alors "en unité" sinon "") || (si borne min >= - 2 000 000 000 et borne max >=0 et borne max < 2 000 000 000 alors "entre borne min et borne max" sinon ""

**Comment by nsenave** [comment]
En java, il y a la possibilité d'utiliser le type `BigInteger` qui n'a pas de valeur limite, donc on pourrait afficher la valeur de la borne (plus simple au final, et sans doute mieux ?).

Pour améliorer l'affichage, je peux ajouter un séparateur de milliers dans la description, qu'en penses-tu ?

PS : j'ai vérifié : dans le Pogues json, dans le DDI et dans le questionnaire Lunatic json, on a bien la borne saisie dans Pogues qui apparaît (les nombres élevés ne se "perdent" pas au passage).

**Comment by AnneHuSKa** [comment]
@nsenave Ca serait top oui (on nous a demandé ce séparateur de milliers mais j'ai à ce jour mis en stand by) donc si tu peux, ca serait top !
