### ISSUE TITLE
Créer une propriété pour les CheckBox et radio pour affichage horizontal - maj

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#1031]

**Comment by ddecrulle** [comment]
We decided :  `orientation="horizontal"` for this case, orientation could be "horizontal" and "vertical" (the default behavior). 

This props concerns Checkbox (group, one) and Radio.

**Comment by nsenave** [comment]
@ddecrulle Do you want the values for horizontal and vertical to be in upper case, like in other enums of the model?

example:

```json
{
  "componentType": "Radio",
  "orientation": "VERTICAL",
  ...
}
```

**Comment by ddecrulle** [comment]
in lower case it's better, but it's a detail

**Comment by AnneHuSKa** [comment]
@nsenave @ddecrulle 
"orientation": "HORIZONTAL",
"orientation": "VERTICAL" 
Ok dans Eno 3.22.7 !

**Comment by AnneHuSKa** [comment]
@nsenave : dans lunatic, c'est finalement "orientation": "horizontal" donc peux-tu modifier la casse générée stp ?,

**Comment by AnneHuSKa** [comment]
@nsenave : je crois qu'on a toujours HORIZONTAL en majuscules ?

**Comment by nsenave** [comment]
@AnneHuSKa Oui au temps pour moi je n'avais pas monté la version Lunatic-Model qui inclus cette correction.

Corrigé dans la `3.26.4-SNAPSHOT`
