### ISSUE TITLE
[Suggester] Permettre l'affichage du label dans le champ de saisie de réponse (et non de l'id)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#1046]
Suite de https://github.com/InseeFr/Lunatic/pull/900

A la génération d'un suggester, ajouter 

```json
	"optionResponses": [
		{
			"name": "<NOM_VARIABLE>_LABEL",
			"attribute": "label"
		}
	]
```

Exemple :

```json
{
	"id": "lty6d4de",
	"page": "5",
	"response": {
		"name": "SUGGESTERH"
	},
	"hierarchy": {
		"sequence": {
			"id": "ltofsc77",
			"page": "1",
			"label": {
				"type": "VTL|MD",
				"value": "\"I - \" || \"S1\""
			}
		},
		"subSequence": {
			"id": "lty68rob",
			"page": "5",
			"label": {
				"type": "VTL|MD",
				"value": "\"Test suggester hors boucle\""
			}
		}
	},
	"mandatory": false,
	"storeName": "L_NATIONALITE-1-2-0",
	"componentType": "Suggester"
}
```

devient 

```json
{
	"id": "lty6d4de",
	"page": "5",
	"response": {
		"name": "SUGGESTERH"
	},
	"optionResponses": [
		{
			"name": "SUGGESTERH_LABEL",
			"attribute": "label"
		}
	],
	"hierarchy": {
		"sequence": {
			"id": "ltofsc77",
			"page": "1",
			"label": {
				"type": "VTL|MD",
				"value": "\"I - \" || \"S1\""
			}
		},
		"subSequence": {
			"id": "lty68rob",
			"page": "5",
			"label": {
				"type": "VTL|MD",
				"value": "\"Test suggester hors boucle\""
			}
		}
	},
	"mandatory": false,
	"storeName": "L_NATIONALITE-1-2-0",
	"componentType": "Suggester"
}
```

**Comment by nsenave** [comment]
A priori, ce besoin est couvert par : 

- #1006 

i.e. si la nomenclature contient l'attribut `"label"`, le questionnaire Pogues/DDI contiendra les infos qui font que Eno va générer les `"optionResponses"` dans le questionnaire Lunatic.

Ce n'est pas encore clair pour moi si ça sera systématique ou si c'est au choix du concepteur.

Dans le deuxième cas, si le concepteur ne spécifie pas de "option response" pour le label, est-ce qu'on souhaite que Eno l'ajoute quand même dans tous les cas si la nomenclature possède l'attribut `"label"` ? (mais voir d'abord l'aspect systématique ou non)

**Comment by AnneHuSKa** [comment]
@nsenave : en fait, toutes les nomenclatures ont un `"label"` et on n'identifie pas de cas où on ne souhaiterait pas l'afficher en cas de retour sur la question. Eventuellement des cas avec `"label + identifiant" (département et son code) mais dans ce cas c'est le `"label"` qui comporte toute l'information donc `"label"`

**Comment by nsenave** [comment]
Il y a un aspect gênant à proposer ce fonctionnement.

Pour reformuler, à partir de : 

```json
{
  "componentType": "Suggester",
  "storeName": "SOME_NOMENCLATURE",
  "response": {
    "name": "TOTO"
  }
}
```

obtenir : 

```json
{
  "componentType": "Suggester",
  "storeName": "SOME_NOMENCLATURE",
  "response": {
    "name": "FOO"
  },
  "optionResponses": [
    {
      "name": "FOO_LABEL",
      "attribute": "label"
    }
  ]
}
```

Cela implique de créer la variable collectée `"FOO_LABEL"` dans les `"variables"` du questionnaire.

Conséquences :

- risque de doublons (ça on peut gérer mais c'est toujours un peu casse-pieds)
- la variable existera dans le questionnaire Lunatic, mais pas dans le DDI (=> problèmes à l'aval par exemple) et ça c'est vraiment gênant

Je pense que pour l'instant, il vaut mieux que l'utilisateur saisisse les formules avec "`left_join`" pour ajouter les "optionResponses" qui correspondent au "label", et attendre que l'UI de Pogues intègre proprement ces concepts, avec notamment l'obligation pour l'utilisateur de saisir/générer les variables correspondantes.

**Comment by nsenave** [comment]
à traiter dans Pogues cf. commentaire ci dessus

**Comment by AnneHuSKa** [comment]
merci. 
@JulienCarmona @lailabent Preneuse d'un exemple final quand il sera dispo pour échanger / valider avec Traiter

**Comment by JulienCarmona** [comment]
Validation QF : ⚠ 
À partir d'un suggester dans 
    - une question à choix unique ✅ 
    - un tableau ❌ 

Testé avec le questionnaire suivant pour le choix unique [response_1729065624611.json](https://github.com/user-attachments/files/17391528/response_1729065624611.json)

Pour le tableau, on n'arrive pas à générer la visu DSFR.
On a l'erreur suivante
```
Unknown error during generation: java.lang.NullPointerException: Cannot invoke "fr.insee.lunatic.model.flat.Suggester.getOptionResponses()" because "suggester" is null
```

**Comment by nsenave** [comment]
En effet la génération de la réponse "multi variables" (`"optionResponses"` dans Lunatic) n'était pas couverte pour des suggester faisant partie d'un tableau (`Table` ou `RosterForLoop`).

Le dev pour supporter ce cas est fait, mais en testant je n'ai pas réussi à reproduire le bug que tu signales @JulienCarmona : en utilisant le [questionnaire Pogues](https://github.com/user-attachments/files/17391528/response_1729065624611.json) que tu donnes, la visu "Web v3" fonctionne (Eno `3.27.1`).

**Comment by JulienCarmona** [comment]
Effectivement, je viens de tester sur le questionnaire en QF m1holrzl et ça semble fonctionner correctement.

Et bien, on ne va pas se plaindre que ça marche ! peut-être qu'il y avait une incohérence dans les versions Pogues/Eno, je ne sais pas trop.
Pour moi c'est bon donc si tu es ok je passe ce ticket à Done et on pourra déployer ça à la prochaine release.

**Comment by JulienCarmona** [comment]
Validation ✅
