### ISSUE TITLE
Personnaliser les bornes (min et max) tableaux dynamiques

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#1055]
Lorsque https://github.com/InseeFr/Pogues/issues/762 sera faite, générer le Json Lunatic correspondant.
**Rappel du besoin à couvrir** : affichage d'un tableau dynamique dont la première colonne est préremplie avec un nb de lignes déterminé dans le fichier échantillon (et donc différent d'une unité à l'autre).

Exemple cible
![image](https://github.com/user-attachments/assets/f1fb5dd9-4e55-4478-8867-cb3fb78753bf)

Actuellement on ne sait faire que cela : 
![image](https://github.com/user-attachments/assets/d234c0e3-055f-4703-9e3a-3ec38c1e2a84)
(produit 2 et produit 3 sont masqués si on met 1 par défaut).

**Comment by nsenave** [comment]
Doublon, voir: 
 
- https://github.com/InseeFr/Bowie/issues/113
- https://github.com/InseeFr/Eno/issues/1114
- https://github.com/InseeFr/Eno/issues/1116

**Comment by JulienCarmona** [comment]
je close car duplicate

**Comment by JulienCarmona** [comment]
Duplicate of 
- https://github.com/InseeFr/Concevoir-Workplace/issues/14
