### ISSUE TITLE
Calcul de variables agrégeant des données calculées de tableaux dynamiques

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#1079]
## Describe the bug

Un rosterForLoop avec 2 colonnes.
On veut faire la somme de la 2eme colonne, en prenant en compte le null : on crée donc une variable qui vaut nvl(Colonne2,0).
La somme de cette nouvelle variable vaut 0

Testé également en prenant le double de la deuxième colonne

=> I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

[issue.json](https://github.com/user-attachments/files/16179733/issue.json)

- Charger le json joint
- saisir 2 montants dans la 2eme colonne
- Constater que la déclaration ne se met pas à jour.

Test fait : le nvl(Colonne2,0) se calcule bien, donc portée ok.

## Expected behavior

Agréger des variables calculées au niveau de l'occurrence - comme pour les boucles

## Screenshots
 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/9d35dd54-5acd-44a8-af9d-cf523987abcb)

## Version where the bug appeared

Lunatic 3.0

## Browser where the bug was tested
 
  Firefox

**Comment by Grafikart** [comment]
Une première piste serait de pouvoir avoir plusieurs variable dans le shapeFrom (avec un système qui prendrait la variable la plus longue.

**Comment by AnneHuSKa** [comment]
3.26.1-SNAPSHOT / OK

**Comment by nsenave** [comment]
Pour mémoire : 

- #1101
