### ISSUE TITLE
Generation of questionnaire CAWI/CAPI with loop leads to 💥  

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Eno#1099]
When making a simple questionnaire with a loop, the questionnaire is impossible to generate in cawi/capi lunatic

Error => Unknown error during generation: java.lang.NullPointerException: Cannot invoke "fr.insee.eno.core.model.question.Question.getName()" because "question" is null

Same result for transformations 'Pogues -> Lunatic' and 'ddi -> Lunatic'

version : 3.26.1-SNAPSHOT

**Comment by AnneHuSKa** [comment]
3.26.3 : ok
