### ISSUE TITLE
Eno Xml - transformation xforms - zip incorrect

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#1112]
## Describe the bug

La génération des xforms et des fo n'est pas (plus) correctement "encapsulée".
- Lorsqu'on utilise le end point [/questionnaire/ddi-2-xforms](https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Generation%20of%20questionnaire%20(custom%20parameters)/generateXformsCustomParams)
[Eno Xml service] Xforms questionnaire generation from DDI : le fichier produit est un xhtml par exemple alors qu'on attend un zip (du genre celui en pj ci-dessous)
- Lorsqu'on utilise le end point [/questionnaire/{context}/xforms](https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Generation%20of%20questionnaire%20(standard%20parameters)/generateXforms)
[Eno Xml service] Xforms questionnaire generation from DDI, le zip créé n'est pas valide
![image](https://github.com/user-attachments/assets/0450b831-fdc2-4327-845d-8bdbe96d6be9)

De plus le xhtml ne semble pas bien encodé, 
![Image](https://github.com/user-attachments/assets/44e63d3f-a3ae-4b1c-8ce3-a50760370542)

## To Reproduce
 Utiliser les fichiers joints
[ddi_meta_params.zip](https://github.com/user-attachments/files/17210712/ddi_meta_params.zip)
et constater le mauvais nommage ou le souci sur le zip.

## Expected behavior
 Un fichier zippé du type  : 
[acemotpe-2023-a00.zip](https://github.com/user-attachments/files/17210744/acemotpe-2023-a00.zip)

(généré avec https://eno-lunatic-v1.dev.kube.insee.fr/swagger-ui/index.html#/Integration%20of%20questionnaire/generateXforms)

qui peut être directement intégré par les batchs Coltrane.

## Additional context
Le souci semble le même pour les fo. Voir si la correction sur xforms déclenche une solution sur fo ?

**Comment by nsenave** [comment]
estimé à 2pt

**Comment by JulienCarmona** [comment]
## Validation QF  - SUITE
En prenant en input les fichiers suivants [ddi_meta_params.zip](https://github.com/user-attachments/files/17210712/ddi_meta_params.zip)
App | Versions
-- | --
Eno Java version | 3.29.0-SNAPSHOT (Release note)
Eno XML web service | http://bowie-qf-eno-ws-xml
DDI version | 3.3
Pogues Model version | 1.3.14
Lunatic Model version | 3.15.1

### Résultats ⚠ -> ✅ 
- end point [/questionnaire/{context}/xforms](https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Generation%20of%20questionnaire%20(standard%20parameters)/generateXforms) ✅ 
On obtient le questionnaire suivant qui est valide [questionnaires.zip](https://github.com/user-attachments/files/17658860/questionnaires.zip)
- end point [/questionnaire/ddi-2-xforms](https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Generation%20of%20questionnaire%20(custom%20parameters)/generateXformsCustomParams) ❌  -> ✅ 
On obtient le fichier zip est pas valide [questionnaires.zip](https://github.com/user-attachments/files/17658903/questionnaires.zip)
Le problème venait du fichier de params de test qui n'avait pas la balise `<pipeline>`
Cela fonctionne si on la rajoute
Au besoin, on peut récupérer un fichier de param valide avec ce endoint 
https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Parameters%20(Eno%20Xml)/getXmlParameters

**Comment by JulienCarmona** [comment]
Le nom n'est pas bon. Je crée un nouveau ticket pour ça
