### ISSUE TITLE
[Rond point - contrôles] Analyse et compréhension de la modélisation DDI

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Eno#1119]
# User Story

**En tant que** developpeur, je veux pouvoir comprendre la modélisation DDI du rond-point et de ses contrôles
**Afin de** pouvoir générer correctement l'attendu

# Definition of Done
- [x] Documentation DDI écrit dans le code en markdown dans Eno
- [x] Peux-être ajouter la doc directement ici : https://github.com/InseeFr/ddi-questionnaire-modeling / https://inseefr.github.io/ddi-questionnaire-modeling/ ?
- [x] Documentation validé par l'équipe

**Comment by nsenave** [comment]
En attente de relecture : 

- https://github.com/InseeFr/ddi-questionnaire-modeling/pull/22

**Comment by JulienCarmona** [comment]
Doc validée et merged, je close ce ticket
