### ISSUE TITLE
Bug visu - Boucle de page Xforms

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Eno#1134]
## Describe the bug

La séquence sur laquelle on boucle apparait sur toutes les pages quand le filtre indique qu'il faut la faire apparaître.

## To Reproduce

1. With the survey `m1tj4366`  in PROD
3. Click on the date picker and select a date > 01/01/2024
4. See module/seq 5 that is display below

## Expected behavior

On ne devrait pas avoir la séquence qui s'affiche à tort sur toutes les pages,

## Screenshots

![image](https://github.com/user-attachments/assets/aa80c4f3-100c-4bfc-86a0-f76c6eedd5ae)

![image](https://github.com/user-attachments/assets/7699dc26-387d-40e5-b4da-9cb2424b2727)

## Version where the bug appeared

[Pogues 1.7.2](https://github.com/InseeFr/Pogues/releases/tag/1.7.2)
[Eno 3.27.1](https://github.com/InseeFr/Eno/releases/tag/3.27.1)

## Additional context

Quand on met '' pour la valeur de date du filtre le comportement est bon : pas d'apparition à tort de la séquence avec la boucle

**Comment by BulotF** [comment]
Le filtre était du style : 
Le répondant est sur la bonne page et la date n'est pas nulle ou la date est récente.
Qui était interprété en : 
(Le répondant est sur la bonne page et la date n'est pas nulle) ou la date est récente.

Correction : rajouter les parenthèses autour de la condition : la date n'est pas nulle ou la date est récente

**Comment by nsenave** [comment]
Fix dans Eno-WS "Xml" `2.6.0` (Eno lib `2.11.0`)

**Comment by JulienCarmona** [comment]
## Validation QF
En prenant en input les fichiers suivants [ddi_meta_params.zip](https://github.com/user-attachments/files/17210712/ddi_meta_params.zip)
App | Versions
-- | --
Pogues | [1.7.3-rc.3](https://github.com/InseeFr/Pogues/releases/tag/1.7.3-rc.3)
?? | 4.2.7 ??
Eno WS Java | [3.29.0-SNAPSHOT](https://github.com/InseeFr/Eno/tree/3.29.0-SNAPSHOT)
Eno WS XML | [2.6.0](https://github.com/InseeFr/Eno-WS/tree/2.6.0)

### Résultats ✅ 
On a bien la partie V qui n'est pas affichée quand on sélectionne dans le date picker une date > 01/01/2024
![image](https://github.com/user-attachments/assets/fd25afe5-f63b-4cfb-a4dc-9a7a33c7b937)
