### ISSUE TITLE
Fix nb occurence de DDI -> Lunatic pour TAB Dynamique à dim fix

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Eno#1136]
### Contexte
Lorsqu'on a une boucle liée à un tableau dynamique de dimension fix...

### Bug 
Alors le nb d'occurrence dépend de la première variable Collected.

Solution :
Alors le nb d'occurrence de la boucle liée est celle du tableau dynamique.

À faire après ce dev https://github.com/InseeFr/Concevoir-Workplace/issues/14

**Comment by nsenave** [comment]
Concrètement dans Eno : 

- Si un tableau dynamique de taille définie en VTL 
- Alors la boucle liée à ce tableau a la même expression dans le champ qui définit sa taille (l'existant étant `count(<première collectée du tableau>)`)

**Comment by lailabent** [comment]
Migrée dans tuleap https://tuleap.insee.fr/plugins/tracker/?aid=9939
