### ISSUE TITLE
JavaDoc warnings

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Eno#114]
5 warnings raised by OSSRH during Eno publication:

- fr\insee\eno\Constants.java:150: no @param for path (getInputStreamFromPath
- fr\insee\eno\xsl\FodsToXSLCompiler.java:33: no description for @param args
- fr\insee\eno\xsl\FodsToXSLCompiler.java:418: no description for @throws Exception
- fr\insee\eno\xsl\FodsToXSLCompiler.java:524: no description for @throws Exception
- fr\insee\eno\xsl\FodsToXSLCompiler.java:621: no description for @throwsException

**Comment by AnneHuSKa** [comment]
done
