### ISSUE TITLE
Roundabout : declarations are not in lunatic-json

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Eno#1143]
## Describe the bug

On Pogues, for a roundabout you can add declarations.
-> in ddi, the declaration is present 👍 
-> in lunatic-json, it should be converted into a description (the component Roundabout can alreadyread it), but currently it is not present so you lose your declaration 👎

**Comment by nsenave** [comment]
Estimé à 5 : ça devrait être léger, il doit juste manquer quelques lignes de code entre le modèle Eno et Lunatic, mais il faudra vérifier que la doc DDI est correcte et peut-être ajouter (ou plutôt mettre à jour) un questionnaire de test.

**Comment by JulienCarmona** [comment]
Close car dans Tuleap maintenant https://tuleap.insee.fr/plugins/tracker/?aid=10070
