### ISSUE TITLE
Eno Xml - Wrong zip name

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Eno#1149]
## Bug
              Le nom du zip n'est pas bon, questionnaire.zip
              Il devrait être égale au nom sous orbeon/fr/XXXX dans l'arborescence de dossier du zip

_Originally posted by @JulienCarmona in https://github.com/InseeFr/Eno/issues/1112#issuecomment-2462588181_

## To Reproduce
1. Aller sur les endoints 
  - [/questionnaire/ddi-2-xforms](https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Generation%20of%20questionnaire%20(custom%20parameters)/generateXformsCustomParams)
  - [/questionnaire/{context}/xforms](https://api-generation-questionnaires-dev.recette.insee.fr/swagger-ui/index.html#/Generation%20of%20questionnaire%20(standard%20parameters)/generateXforms)
3. Utiliser en input les fichiers joints
[inputEnoToXFORMS.zip](https://github.com/user-attachments/files/17664458/inputEnoToXFORMS.zip)
4. Constater le mauvais nommage du zip.
[questionnaires.zip](https://github.com/user-attachments/files/17664602/questionnaires.zip)

## Expected behavior
 Un fichier zippé du type  : 
[acemotpe-2023-a00.zip](https://github.com/user-attachments/files/17210744/acemotpe-2023-a00.zip)
(généré avec https://eno-lunatic-v1.dev.kube.insee.fr/swagger-ui/index.html#/Integration%20of%20questionnaire/generateXforms)

Dans le cas de notre fichier questionnaires.zip, on devrait avoir le nom `test-2020-x00.zip` au vu de son contenu

**Comment by RemiVerriez** [comment]
**Récapitulatif** des actions à réaliser suite à l'entrevue avec @JulienCarmona.

- La procédure pour corriger le bug est claire et mise en place pour les endpoints "ddi-2-fo" et "ddi-2-xforms" des "custom parameters" (obtention du paramètre "campagne" personnalisé).

- Cette procédure doit être modifiée/complétée pour permettre de résoudre le problème concernant les endpoints "{context}/fo" et "{context}/xforms" des "standard parameters" (obtention du paramètre "campagne" non personnalisé via le endpoint "GET" ?).

- Aucun changement de nommage ne doit être appliqué pour tous les autres endpoints. 

- Des exceptions sont à créer pour gérer les balises manquantes/vides du paramètre "campagne" (il ne doit pas être possible de générer un zip/fichier dans de telles situations).

**Comment by nsenave** [comment]
Suite de cette US : 

- https://github.com/InseeFr/Concevoir-Workplace/issues/72

**Comment by nsenave** [comment]
Pour cette issue : c'est fait dans la version `3.29.3-SNAPSHOT`, en attente de validation.

**Comment by JulienCarmona** [comment]
# Validation QF ❌ 

App | Versions
-- | --
Eno Java | [3.30.0-SNAPSHOT.1](https://github.com/InseeFr/Eno/tree/3.30.0-SNAPSHOT.1)
Eno XML | [2.6.0](https://github.com/InseeFr/Eno-WS/tree/2.6.0)

J'ai toujours un `questionnaire.zip` quand j'essaye de générer un xforms avec les fichiers suivants
[inputEnoToXFORMS.zip](https://github.com/user-attachments/files/18065025/inputEnoToXFORMS.zip)
J'ai bien une balise `<Campaign>` dans mon `paramters-simple.xml` pourtant

**Comment by nsenave** [comment]
@JulienCarmona ce correctif nécessite la version `2.6.1-SNAPSHOT.2` d'Eno xml

my bad c'était pas déployé sur notre env de recette, mais c'est le cas maintenant

**Comment by JulienCarmona** [comment]
# Validation QF ✅ 

App | Versions
-- | --
Eno Java | [3.30.0-SNAPSHOT.1](https://github.com/InseeFr/Eno/tree/3.30.0-SNAPSHOT.1)
Eno XML | [2.6.1-SNAPSHOT.2](https://github.com/InseeFr/Eno-WS/tree/2.6.1-SNAPSHOT.2)

J'obtiens bien un [test-2020-x00.zip](https://github.com/user-attachments/files/18081723/test-2020-x00.zip) quand j'essaye de générer un xforms avec les fichiers suivants
[inputEnoToXFORMS.zip](https://github.com/user-attachments/files/18065025/inputEnoToXFORMS.zip)
Si je change le nom de la balise <Campaign> avec `<Campagne>test-name-edited</Campagne>` j'obtiens bien [test-name-edited.zip](https://github.com/user-attachments/files/18081777/test-name-edited.zip)


⚠ Pour l'api avec les standards parameters, j'ai toujours `questionnaire.zip` mais ce sera fait ici 
- https://github.com/InseeFr/Concevoir-Workplace/issues/72
