### ISSUE TITLE
Control Roundabout - Can't have Except field with Occurence level control

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Eno#1156]
## Describe the bug

Occurence level control on roundabout aren't displayed if the except field is filled

## To Reproduce

1. Create a survey with a roundabout
2. Fill the except field
3. Add a control on Occurence level with `true` as display condition and any error message
4. Launch a Web visu
5. go to roundabout page
6. click on continue
7. BUG : See that the error message is not displayed

## Expected behavior

Control should appear in this case after clicking on continue

## Version where the bug appeared
| Application        |   Version    |
| ------------------ |:----------------:|
| Pogues             |   1.7.3  |
| Pogues-Back-Office |  4.9.1  |
| Stromae DSFR       | 1.2.3  |
| Lunatic - Stromae DSFR  | 3.4.4       |
| Eno-WS Java             |  3.29.0 |
| Eno-WS Xml              |   2.6.0  |

**Comment by nsenave** [comment]
Estimé à 5 : a priori pas beaucoup de code à modifier mais nécessite d'investiguer un peu pour comprendre ce qu'il se passe.

**Comment by lailabent** [comment]
Migrée dans Tuleap https://tuleap.insee.fr/plugins/tracker/?tracker=832&aid=9917
