### ISSUE TITLE
duration variables are missing in loop resizing in json-lunatic

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Eno#1157]
## Describe the bug

In json-lunatic, when making a loop with a dimension calculated by a variable, every variable of the loop should be present in the resizing of this variable (so that when we change its value, it updates the dimension of every variable of the loop).

But currently, if we create a duration question (no matter its format) in a loop, this variable is missing from the resizing.

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

- use directly questionnaire m1ux0exa in pogues-dv ([pogues-json](https://github.com/user-attachments/files/17773997/response_1731666038624.json))
- transform into lunatic

## Expected behavior

In the resizing for the variable (PRENOMS in the example) defining the dimension of the loop (BOUCLE_COMPLETE in the example), the duration variables (HHMMLOOP and AAMMLOOP in the example) should be present just as the other ones

**Comment by nsenave** [comment]
Estimé à 5 car ça touche au resizing. Je pense voir la raison a priori et ça pourrait être rapide, mais possible qu'il y ait des complications.

**Comment by nsenave** [comment]
Bien vu @QRuhier sur le resizing, en effet il y avait bien un loupé dans Eno pour les "duration" Lunatic dans la génération du _resizing_ (couplé à un cas par défaut qui ne renvoyait pas d'exception dans une des méthodes, j'ai corrigé ça).

**Comment by JulienCarmona** [comment]
cf https://github.com/InseeFr/Lunatic/issues/1169#issuecomment-2486353765

**Comment by JulienCarmona** [comment]
ticket close ca validation ✅ 
cf https://github.com/InseeFr/Lunatic/issues/1169#issuecomment-2491981016

**Comment by JulienCarmona** [comment]
@nsenave est-ce qu'on peut en faire une release pour pouvoir deployed cette correction

**Comment by nsenave** [comment]
Prêt à être mis en prod dans la release publiée en `3.29.1`, désolé pour le délai
