### ISSUE TITLE
Control - VTL's control in Lunatic model wrong if VTL condition begins with 'not(...' in Pogues VTL diplay condition

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Eno#1164]
## Describe the bug

ENO is not generating correctly VTL expression for control when it begins with `not(...)`

## To Reproduce

1. Create a survey with a question and a control
2. VTL formula of control should start with `not(...) ....`
3. Visualize survey
4. See that in lunatic json model the VTL formula associated to the control is not wright 

exemple with 
Pogues : [m3sz3lir-pogues.json](https://github.com/user-attachments/files/17873688/m3sz3lir-pogues.json)
Lunatic : [m3sz3lir-lunatic.json](https://github.com/user-attachments/files/17873691/m3sz3lir-lunatic.json)

## Expected behavior

the formula should be the same in the lunatic-json.json

## Screenshots
![{C977480D-9138-4BAD-9CAB-DD38FF47A0B3}](https://github.com/user-attachments/assets/002ed278-4037-4e09-8da8-2fa2f3f70f0f)
![{686142FF-4EC1-4B4D-8A08-D257F5EC6BF7}](https://github.com/user-attachments/assets/c1f6d279-646c-49f9-8c37-3935ff41f8fb)

## Version where the bug appeared

 Eno Java version | [3.29.0](https://github.com/InseeFr/Eno/releases/tag/3.29.0)

## Additional context

if there is a `not` at the beginning of VTL formula, it's like it's doing a `not(not(...` so it just deletes it but if the `not` is not covering the whole VTL formula we have an issue
Eg : `not($Q$<5) and true and not(false)` -> `Q<5) and true and not(false`

**Comment by nsenave** [comment]
corrigé par : 

- #1166 

Version `3.29.0-hotfix.1`

**Comment by JulienCarmona** [comment]
# Validation QF  
Survey ex : 
[m3sz3lir-pogues.json](https://github.com/user-attachments/files/17936902/m3sz3lir-pogues.json)


App | Versions
-- | --
Eno Java | [3.29.0-hotfix.1](https://github.com/InseeFr/Eno/tree/3.29.0-hotfix.1)
Eno XML | [2.6.0](https://github.com/InseeFr/Eno-WS/tree/2.6.0)
Pogues | [1.7.4-rc.0](https://github.com/InseeFr/Pogues/releases/tag/1.7.4-rc.0)
Pogues Back Office | [4.9.2-SNAPSHOT.1](https://github.com/InseeFr/Pogues-Back-Office/tree/4.9.2-SNAPSHOT.1)
stromae-dsf/Lunatic | [1.3.0-rc.4](https://github.com/InseeFr/stromae-dsfr/tree/v1.3.0-rc.4) / [3.4.7](https://github.com/InseeFr/Lunatic/tree/3.4.7)

## Résultats ✅ 
Lunacti model : 
[m3sz3lir-lunatic.json](https://github.com/user-attachments/files/17936905/m3sz3lir-lunatic.json)
- ✅ On a bien le `not(` au début et la `(` à la fin qui restent dans la formule TLV du contrôle dans le fichier le m3sz3lir-lunatic.json
![{4EEEF31C-8D2B-4BBE-ABD2-487376C97BEE}](https://github.com/user-attachments/assets/e6f80ede-33bf-417c-858d-88bd8ff112f5)
![{C7CC7D1E-8BC9-49A3-9053-0B875C906031}](https://github.com/user-attachments/assets/37b1a607-a7ad-4992-ad2e-9e05b3406023)

**Comment by nsenave** [comment]
Pour mémoire si jamais : version `3.29.0-hotfix.2` (par rapport à la `.1` montée de version open api pour que swagger fonctionne après la montée de version spring)
