### ISSUE TITLE
Internationalization of controlled vocabulary

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#14]
Look for a way to internationalize the controlled vocabulary used by eno.
It might not be doable but it needs to be investigated.

**Comment by Mugiwara84** [comment]
It might easily be done by translating the controlled vocabulary used to english before entering eno main process.
But is it really necessary since Insee uses english controlled vocabulary now ?

**Comment by ORogel** [comment]
Internationalisation has been done in 2021.
