### ISSUE TITLE
Improvement of Markdown processor 

### ISSUE THREAD

**Issue by aude-mulliez** [InseeFr/Eno#188]
We want to transform XMLPogues to DDI (in fact to obtain JSON Lunatic files) but it fails when some of our attributes (Label, name, id) contain "*" characters.

The error we receive is : 
{
  "status": 500,
  "message": "Transformation error",
  "details": "fr.insee.pogues.transforms.PoguesXMLToDDIImpl:org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 65; Le type d'élément \"xhtml:i\" doit se terminer par la balise de fin correspondante \"</xhtml:i>\"."
}

We do not want tot rename our questionnaires/questions, so it would be great if we can use "*" ! Thanks !

**Comment by bibirico** [comment]
This is issue is coming from the markdown-to-xhtml transformation used to style the label of DDI elements.
If you don't need this kind of styling (as italic, bold, and so on), you could tweak the script [build-pogues-xml2ddi.xml](https://github.com/InseeFr/Eno/blob/master/src/main/scripts/build-pogues-xml2ddi.xml) and squeeze the ant target called `DDIPostProcessing` in charge of the markdown transformation. Care, just skipping it won't be enough, you'll have to retrieve the correct output file name in the next step or the pipeline will break (`DDIPostProcessing` is producing a file named `${root-folder}/target/${survey-name}/ddi-test/${survey-name}-outBO-with-html` which is expected by the next step, so change the output file name of the previous step, or the input file name of the next step).

We should have a build with this markdown styling in option as it has syntax constraints (as no '*' in your label outside markdown styling)... TODO.

**Comment by romaintailhurat** [comment]
That's still a pending issue, with application to every text fields where Markdown has to be processed.

A real treat would be to re-engineer Eno Markdown processor in order to be Markdown compliant.

A simple re-use case: `This is a md **text***` (with a supplementary star).

**Comment by romaintailhurat** [comment]
Slight update: we may support the escape character `\`, which would allows to write `This sentence has a star\*` and render `This sentence has a star*`
