### ISSUE TITLE
Remove the redundant zip file containing the Simpsons test questionnaire

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#3]
[Here](https://github.com/InseeFr/Eno/tree/master/doc) we have a zip file holding a version of the Simpsons questionnaire, but it has been recently pushed in another - and more appropriate ? - [location](https://github.com/InseeFr/Eno/tree/master/questionnaires/simpsons/DDI), so i guess the zip file can be deleted.

**Comment by Mugiwara84** [comment]
It's done !
