### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by FBibonne** [InseeFr/Eno#350]
The "process-classes" phase of the build process has one issue and can be improved :
1. Issue : in order to respect the maven build lifecyle logical, the generated xsl files should  not be copied in the src/main directory since after the compile phase in the build lifecycle maven doesn't any more take into account files in src/main. Generated files should be copied in the target directory (`FodsToXSLCompiler.class.getClassLoader().getResource(".")` to get target directory path)
2. the version of exec-maven-plugin used (1.21) is 9 years old. Move to 3.0.0
3. Change to plugin conf to correctly log :
```
<property>
    <key>log4j.configurationFile</key>
    <value>${project.basedir}/src/test/resources/log4j2-test.xml</value>
</property>
...
<configuration>
   <classpathScope>test</classpathScope>
</configuration>
```

**Comment by ORogel** [comment]
Done.
