### ISSUE TITLE
Moving final template of dereferencing.xsl ?

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#41]
It is the template on xhtml:a.
It seems to me that it is not correctly placed.
Is it really dereferencing ?
Wouldn't it be more appropriate to :
- create a driver in some way to write the HTML in models.xsl ?
- or at least to move it in cleaning.xsl where some templates linked to xhtml:a elements are already present ?

**Comment by BulotF** [comment]
Kept only for tooltips, because it is a real reference.
