### ISSUE TITLE
Mutualise some elements in resource instance in the Xforms output ?

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#43]
For example, the alert message :
'You shall type an integer number between _**x**_ and _**y**_" is written a lot in the resource instance.
It should be possible to do something approximately like this :
1) write only once in the resource instance :
<messageA>You shall type an integer number between</messageA>
<messageB>and</messageB>
2) call the alert message like this in the xforms element :
<xf:alert value="concat($form-resources/messageA, x, $form-resources/messageB, y)"/>
Approximately...

Would it really decrease the size of the questionnaire ?
Would it be faster/slower/the same ?

**Comment by ORogel** [comment]
Xforms will be dismissed in the future by Insee.
