### ISSUE TITLE
Redesign the process around the DoubleDuration driver

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#49]
The usage of this driver is weird and it is not at all generic.
It creates two xforms controls from a unique ResponseDomain.
And it indicates that the select values can only be between 20 and 60 in the output.
The driver is not reusable in that state.

**Comment by bibirico** [comment]
We need to fix this for the pdf output implementation.

**Comment by BulotF** [comment]
Done : there is, since beginning of 2019, a generic driver for durations
