### ISSUE TITLE
enoddi:get-output-format is Xforms orientated

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#50]
It should return the values 'radio-button', 'drop-down-list' and 'checkbox' and not the values 'full' and 'minimal'.
The enofr:get-appearance function must not be directly linked to the enoddi:get-output-format.
The values 'full' and 'minimal' must be deduced from enoddi:get-output-format and enoddi:get-type in ddi2fr-fixed.xsl.

**Comment by BulotF** [comment]
Done since september 2019
