### ISSUE TITLE
[Eno V3] Loop implementation

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#526]
Eno core: Loop mapping from DDI to Lunatic.

**Comment by AnneHuSKa** [comment]
J'ai un écran orange dès la première boucle : 
https://visu-stromae-v2-sandbox.demo.insee.io/visualize?questionnaire=https%3A%2F%2Fpogues-back-office-enov3.demo.insee.io%2Fapi%2Fpersistence%2Fquestionnaire%2Fjson-lunatic%2FINSEE-lb3ei722

**Comment by AnneHuSKa** [comment]
Je n'arrive pas à écrire/saisir des données dans la première question des boucles principales

Autres (comparaison des json) : 
-  je vois              "loopDependencies": [
                "NB",
                "NB"
            ],
- je vois          "iterations": {
                "value": "count(PRENOM)"}
							 
	au lieu de             "iterations": {
                "value": "count(PRENOM)",
                "type": "VTL"
            }


[Liens2a2.zip](https://github.com/InseeFr/Eno/files/12537583/Liens2a2.zip)

**Comment by nsenave** [comment]
Reste à faire : #577 en cours

cf InseeFr/Lunatic-Model#116
