### ISSUE TITLE
[Eno V3] Lunatic questionnaire: optimisation blocks

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#555]
## Overview

In Lunatic out format: blocks `"cleaning"`, `"missing"` and `"resizing"`. These blocks correspond to logic operations to be evaluated during the questionnaire. Eno writes them so that Lunatic has less computation to do.

They are not implemented yet in Eno java.

## Features

- [x] #558 
- [x] #557 
- [x] #556

**Comment by AnneHuSKa** [comment]
Dans le projet, découpé en issues => sorti du sprint
