### ISSUE TITLE
[Eno V3] Lunatic `"resizing"` block

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#556]
## Overview

Lunatic questionnaires contain a `"resizing"` block: the use case is to empty some array variable values when the variable that defines the size of the array changes.

Eno v3 doesn't write this block in Lunatic questionnaires yet.

## Spec

In Lunatic questionnaires:

```json
{
  "resizing": {
    "SOME_VARIABE": {
      "size": "nvl(SOME_VARIABE,1)",
      "variables": [
        "CONCERNED_VARIABLE1",
        "CONCERNED_VARIABLE2",
        "..."
      ]
    }
  }
}
```

**Comment by davdarras** [comment]
Exemple du format json pour le resizing: 
```
{
  "resizing": {
    "NBPERS": {
      "size": "nvl(NBPERS,1)",
      "variables": ["THL_PRENOM", "THL_AGE", "TAILLE"]
    },
    "NBLINK": {
      "size": "nvl(LINK,1)",
      "variables": ["THL_LINK", "THL_LINK_NAME"]
    },
    "G_PRENOM": {
      "sizeForLinksVariables": ["count(PRENOM)", "count(PRENOM)"],
      "linksVariables": ["LIENS"]
    }
  }
}
```
Le resizing permet de changer la taille d'un tableau (si l'utilisateur entre 3 lignes, commence à remplir les champs et reviens sur le nombre de lignes pour dire finalement qu'il y en a 2, cela permet de virer les champs en trop précédemment remplis)

Le resizing se fait sur: 
- LOOP
- PAIRWISE_LINKS
- ROSTER_FOR_LOOP (tableau dynamique)
- ~~Boucle de boucle~~ ==> Pas de modélisation pour le moment

LOOP: Pour calculer le resizing, lorsqu'on traite la boucle "principale", on récupère aussi les variables des boucles liées via le VariableGroup. A voir avec nico comment distinguer la boucle "principale" (lines/max ?) de ses boucles liées (iterations/values ?).  

Exemple
```
    "NBPERS": {
      "size": "nvl(NBPERS,1)",
      "variables": ["THL_PRENOM", "THL_AGE", "TAILLE"]
    }
```

Pour générer le resizing, on récupère l'attribut lines/max de chacune des boucles principales. Si l'attribut max est un nombre, pas de resizing, on passe à la boucle suivante. Si c'est une  formule, alors pour chaque variable de la formule (à voir avec nico comment récupérer les variables d'une formule sur une boucle): 
1/ Si la variable de la formule est collectée: 
- on créé un objet resizing ayant pour clé d'object le nom de la variable
- l'attribut "size" de l'objet correspond à la formule VTL de l'attribut max du composant (attribut lines/max de la boucle sur questionnaire lunatic)
- l'attribut "variables" correspond à la liste des variables (calculées et collectées) nécessaires au calcul de la formule (récupérer les variables de l'objet VariableGroup de la boucle sur le questionnaire ENO), ce qui permet de récupérer les variables de la boucle "principale" et des boucles "liées". Le VariableGroup peut aussi contenir des références à d'autres VariableGroup (boucles imbriquées), à prendre en compte lors du traitement des boucles de boucles

2/ Si la variable de la formule est calculée: 
- on récupère les variables de la formule permettant de calculer cette variable calculée (Variable>CalculatedExpression>BindingReferences sur la modélisation ENO)
- Pour chacune de ces variables:
	- si la variable est collectée, retour à l'étape 1/
	- si la variable est calculée, retour à l'étape 2/

Les objets "resizing" ne correspondent qu'à des variables collectées. Les variables calculées sont remplacées par les variables collectées permettant d'effectuer le calcul de la variable ... calculée.

PAIRWISE_LINKS: 

Exemple:
```
    "G_PRENOM": {
      "sizeForLinksVariables": ["count(PRENOM)", "count(PRENOM)"],
      "linksVariables": ["LIENS"]
    }
```

Pour générer le resizing, on récupère les composants de l'objet pairwise. Pour chacun de ces composants: 
- on créé un objet resizing ayant pour clé d'object le nom du composant
- l'attribut "sizeForLinksVariables" correspond à la liste des formules VTL pour calculer le resizing (xaxisiterations/value, yaxisiterations/value du composant pairwise sur le questionnaire lunatic)
- l'attribut "linksVariables" correspond à la liste des variables (calculées et collectées) au sein du lien 2 à 2 (récupérer les variables de l'objet VariableGroup du pairwise sur le questionnaire ENO).

**Comment by davdarras** [comment]
En attente d'informations complémentaires avant finalisation de l'implémentation technique: 
- où récupérer les variables d'une formule sur une boucle ?
- comment distinguer une boucles liée d'une boucle principale ?
- comment gérer le fait qu'une variable soit utilisée dans plusieurs formules ? (ca marchote pour boucle à coté d'un lien 2 à 2)

**Comment by laurentC35** [comment]
Douloureux mais c'est fait 🎆
