### ISSUE TITLE
[Eno V3] Lunatic `"cleaning"` block

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#557]
## Overview

Lunatic questionnaires contain a `"cleaning"` block: the use case is to empty some variable values when a variable that is used in a filter changes.

Eno v3 doesn't write this block in Lunatic questionnaires yet.

## Spec

In Lunatic questionnaires:

```json
{
  "cleaning": {
    "SOME_VARIABLE": {
      "CONCERNED_VARIABLE1": "<filter expression applied on variable (that uses SOME_VARIABLE)>",
      "CONCERNED_VARIABLE2": "<filter expression applied on variable (that uses SOME_VARIABLE)>"
    }
  }
}
```

**Comment by AnneHuSKa** [comment]
ok 05/09 - un bug restant, nouvelle issue créée
