### ISSUE TITLE
[Eno V3] Lunatic "MISSING" variables

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#558]
## Overview

Lunatic questionnaires can contain "MISSING" variables. The use case: when the respondent answers with "don't know" or "refusal" to a question: some logic is written in Lunatic questionnaires to make sure that corresponding variables are empty. The `"missing"` option in Lunatic questionnaire can be set to false in collection mode where "don't know" or "refusal" is not allowed.

Eno v3 doesn't write this in Lunatic questionnaires yet.

## Spec

In Lunatic questionnaires:

```json
{
  "missing": true,
  "components": [
    {
      "id": "some-question-component-id",
      "...": "...",
      "missingResponse": {
        "name": "SOME_QUESTION_MISSING"
      }
    },
    {
      "id": "some-table-component-id",
      "...": "...",
      "missingResponse": {
        "name": "SOME_TABLE_MISSING"
      }
    }
  ],
  "variables": [
    {
      "variableType": "COLLECTED",
      "name": "SOME_QUESTION_MISSING"
    },
    {
      "variableType": "COLLECTED",
      "name": "SOME_TABLE_MISSING"
    }
  ],
  "missingBlock": {
    "SOME_QUESTION_MISSING": [
      "SOME_QUESTION"
    ],
    "SOME_QUESTION": [
      "SOME_QUESTION_MISSING"
    ],
    "SOME_TABLE_MISSING": [
      "TABLE_VAR1",
      "TABLE_VAR2",
      "TABLE_VAR3",
      "TABLE_VAR4"
    ],
    "TABLE_VAR1": [
      "SOME_TABLE_MISSING"
    ],
    "TABLE_VAR2": [
      "SOME_TABLE_MISSING"
    ],
    "TABLE_VAR3": [
      "SOME_TABLE_MISSING"
    ],
    "TABLE_VAR4": [
      "SOME_TABLE_MISSING"
    ]
  }
}
```

**Comment by davdarras** [comment]
## MISSING

Récupérer tous les composants du questionnaire avec un attribut missingResponse. Pour chacun de ces composants, on traite de la manière suivante pour les **cas standards**: 
- on crée une paire clé/valeur ayant pour clé l'attribut "missingResponse/name" du composant et ayant pour valeur une liste contenant l'attribut "response/name"
- on crée une seconde paire clé/valeur ayant pour clé l'attribut "response/name" du composant et ayant pour valeur une liste contenant l'attribut "missingResponse/name"
 
Exemple: 
```
  "missingBlock": {
    "SOME_QUESTION_MISSING": [
      "SOME_QUESTION"
    ],
    "SOME_QUESTION": [
      "SOME_QUESTION_MISSING"
    ]
   }
```

### Différents cas d'usage

Sequence/Subsequence/Filter: cas à ne pas traiter, ces composants n'ont pas d'attribut response/name

Textarea/Input/InputNumber/DatePicker/CheckboxBoolean/CheckboxOne/Radio/Dropdown
==> Cas standard

Pairwise: il faut récupérer les composants dans l'attribut "components" du lien 2 à 2, qui contiennent l'information concernant les variables "missing" et qui sont à traiter de manière standard.

Boucle de boucle: cas non pris en charge pour le moment

Boucle/Table/RosterForLoop/checkboxGroup: 
- on crée une paire clé/valeur ayant pour clé l'attribut "missingResponse/name" de la boucle/table/roster/checkboxgroup et ayant pour valeur une liste contenant les attributs "response/name" de ses enfants ("components" pour boucle/roster,  "body/" pour table, "responses" pour checkbox group)
- pour chaque enfant ayant un attribut "response/name", on crée une paire clé/valeur ayant pour clé l'attribut "response/name" de l'enfant  et ayant pour valeur une liste contenant l'attribut "missingResponse/name"  de la boucle/table/roster/checkboxgroup

Exemple: 
```
  "missingBlock": {
    "LOOP_MISSING": [
      "LOOP_VAR1",
      "LOOP_VAR2",
    ],
    "LOOP_VAR1": [
      "LOOP_MISSING"
    ],
    "LOOP_VAR2": [
      "LOOP_MISSING"
    ]
  }
```
