### ISSUE TITLE
[EnoV3] QCM et tableaux dans les boucles principales

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#560]
Only when https://github.com/InseeFr/Lunatic/issues/436 is closed

**Comment by nsenave** [comment]
Shouldn't this issue be labeled with `standby`? (i.e. non-blocking for the first production delivery)

**Comment by AnneHuSKa** [comment]
A vérifier avec Lunatic 2.7

**Comment by nsenave** [comment]
Il y a plusieurs sujets liés à cela :

- le fait que les tableaux/qcm s'affichent mal dans Lunatic quand ils sont dans une boucle (à voir s'il y aura quelque chose à changer dans la génération Eno, pas sûr)
- le cas où un composant à réponses multiples (par exemple QCM/tableau) corresponde à la _première_ question d'une boucle, et où il existe une boucle liée à cette boucle. Dans ce cas précis, il y a un peu de code à adapter dans Eno Java pour la génération du composant boucle liée (l'expression VTL avec un "count" dans la propriété "iteration" de la boucle liée). Pour l'instant une erreur est renvoyée si ce cas arrive.

**Comment by AnneHuSKa** [comment]
QCM et tableaux simples sont ok dans les boucles principales.
Mémo : ne pas mettre en première question d'une boucle un QCM.
