### ISSUE TITLE
[Eno V3] ajouter le mode dans le json produit (ou dans le nom fichier produit)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#562]
Cas d'usage : pouvoir vérifier le mode utilisé pour la génération du json

**Comment by nsenave** [comment]
C'est noté, ça sera fait dans Eno v3

**Comment by nsenave** [comment]
Il me semble que c'est le cas pour les paramètres, mais pas pour le questionnaire Lunatic non ?

Ça me semble bien en effet d'ajouter cette info dans le questionnaire Lunatic (dans le nom de fichier et surtout dans le contenu json `"mode": "CAWI"` par exemple)
