### ISSUE TITLE
[Eno V3] absence des values COLLECTED, EDITED etc...

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#577]
Absence des 
     "variableType": "COLLECTED",
      "values": {
        "COLLECTED": null,
        "EDITED": null,
        "INPUTED": null,
        "FORCED": null,
        "PREVIOUS": null
      },
      "name": "QCU1"

Exemples 
[lfsey94u_V2etV3.zip](https://github.com/InseeFr/Eno/files/11333525/lfsey94u_V2etV3.zip)

**Comment by nsenave** [comment]
Question candide : est-ce que ces champs sont réellement utiles pour Lunatic ?

Si oui, j'implémenterai une solution côté [Lunatic-Model](https://github.com/InseeFr/Lunatic-Model) (c'est la responsabilité de Lunatic-Model de sérialiser correctement des objets java Lunatic en json).

**Comment by nsenave** [comment]
Ces champs semblent être inutiles pour les variables au niveau racine du questionnaire, mais pour les variables collectées au sein d'un boucle, il semblerait que l'absence de la partie `"values"` empêche de saisir des valeurs...

Exemple valide d'une variable collectée dans une boucle :

```json
        {
            "variableType": "COLLECTED",
            "name": "PRENOM",
            "values": {
                "PREVIOUS": [null],
                "COLLECTED": [null],
                "FORCED": [null],
                "EDITED": [null],
                "INPUTED": [null]
            }
        }
```

NB : pareil pour les variables des tableaux dynamiques j'imagine

NB 2 : pour les boucles de boucles on aurait `[[null]]` etc.

**Comment by nsenave** [comment]
Implémenté avec des values de la forme :

- `"COLLECTED": []` pour les boucles
- `"COLLECTED": [[]]` pour le pairwise

Il faudra encore vérifier, par exemple avec Public-Enemy, que les données en sortie de l'orchestrateur sont bonnes avec cette implémentation (sans les `null`)

**Comment by AnneHuSKa** [comment]
Présent dans le json et fonctionnel. @romaintailhurat : on pourra tester une intégration PE à l'occasion stp ?

**Comment by QRuhier** [comment]
Tester dans Stromae/Queen

**Comment by nsenave** [comment]
@AnneHuSKa J'ai essayé en visu "Web v2" dans pogues, quand on clique sur "Se déconnecter et quitter" sur la page de fin de Stromae, ça télécharge les données (et paradonnées).

Après avoir testé des questionnaires qui contiennent des boucles : j'ai bien toutes les données saisies dans le fichier de données.

**Comment by AnneHuSKa** [comment]
Ah top !! merci d'avoir vu cela @nsenave ! je ne savais pas et ca sera bien pratique, merci !
