### ISSUE TITLE
Separate the main instance in two ? And flatten the two instances ?

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#58]
Is it possible to separate the main instance in two ?
- some elements are linked to fields and can be filled by end users
- some elements are linked to fixed texts and will never change
Only the first type of elements need to be saved.
The other elements could be put into a second instance.
Two gains :
1) only the data that needs to be saved is saved, it will increase the performances
2) there are less adherences between the form and the data stored in base. If for example we want to change an id element for an unknown reason, it is possible. It's not possible if there is such a mention in base.

And is it possible to flatten the instance ? It will be necessary if we want to remove id sections of the main instance.

**Comment by ORogel** [comment]
No big investment for xforms.
