### ISSUE TITLE
[Eno V3] traitements spécifiques - regroupement de questions

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#587]
[cf issue 586](https://github.com/InseeFr/Eno/issues/586)

Cas 2 : Web : regrouper plusieurs questions sur la même page 
Eno permet de générer un questionnaire (web) comprenant soit une question par page, soit une séquence par page. Ce découpage/cette présentation s’applique à tout le questionnaire et le choix pour les enquêtes ménages est de proposer une question par page (plus responsive). Or on peut souhaiter regrouper des questions sur une même page.

**Description du traitement spécifique** : le TS consiste à modifier le numéro de page pour regrouper des questions sur la même page
**Solution mise en place**
    • le concepteur liste les variables à regrouper 
    • le TS peut alors être adapté par les intégrateurs : nom des variables à regrouper 
**Précaution** : une variable absente du questionnaire provoquera aujourd'hui une erreur d’affichage de tout le questionnaire.
**Cible** : aucune, pas d’évolution prévue – hormis la création d’un composant adresse qui regrouperait tous les champs d’adresse

**Comment by AnneHuSKa** [comment]
[Lunatic_JsonAvecTs.zip](https://github.com/InseeFr/Eno/files/11383884/Lunatic_JsonAvecTs.zip)

**Comment by AnneHuSKa** [comment]
Je ne suis pas certaine que le TS fonctionne quand on a un QCM dans le regroupement (CheckBoxGroup, avec pour modalités de réponses par exemple "QCM_ON1","QCM_ON2","QCM_ON3","QCM_ON4","QCM_ON5"
Exemple en pj, questions 8 et 9
[Json_test_TS.zip](https://github.com/InseeFr/Eno/files/11949967/Json_test_TS.zip)

**Comment by davdarras** [comment]
Aurais tu un exemple pour ce cas sur eno-v2 ?

**Comment by AnneHuSKa** [comment]
Changement de cap : ca ne me semble pas cohérent de le proposer. Quand on regroupe, c'est par exemple pour avoir "oui/non et combien" par exemple ou des précisions. Dans le cas de QCM, je ne vois pas. Donc le TS actuel est ok !

**Comment by romaintailhurat** [comment]
Reste à valider pour les boucles

**Comment by nsenave** [comment]
Les boucles sont en validation et la génération avec ce TS est fonctionnelle : je mets l'issue en validation.

**Comment by AnneHuSKa** [comment]
Impeccable @nsenave
