### ISSUE TITLE
Refactoring the Body//Table and Body//TableLoop templates

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#59]
The second one was inspired by the first one.
And the first isn't completely compliant with the Eno architecture.

In theory, the Table driver should write some elements, call some functions and continue the process with the children of the input.
Those children will call some other drivers, etc....

When I wrote the functionnality, I could not manage to do that, so I use a function to directly get the elements I needed as children and do the treatment within the Table Driver.
Some functions on the DDI side are a little weird.

It will be an improvement to refactor that part.

**Comment by ORogel** [comment]
Totally different now :  not a subject anymore.
