### ISSUE TITLE
EnoV2 - pairwise - bug sur resizing

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#592]
La version Eno permettant de faire le pairwise génère un json qui ne permet pas de modifier la taille de la boucle quand elle a été instanciée une fois (et collectée).

Pb de resizing :
Si si on ne saisit rien, le resizing fonctionne.
Si on saisit des prénoms, donc si on alimente la première boucle on ne peut plus changer sa taille

  "resizing": {
    "NB": {
      "variables": [
        "AGE"
      ],
      "size": "cast(NB,integer)"
    }

=> il manque la variable de la boucle principale.
________________________________________________________________________
échanges avec FB ; 

le Eno-ws 1.6.1 fonctionne pour les resizing ; pas la version 1.6.2-rc : il y a eu régression entre les deux…

Je pense plus sérieusement que le 1.6.2-rc a pu partir d’une version antérieure à la 1.6.1 et qu’il n’a pas récupéré une des évolutions

Pour info :
En prod (où ça fonctionne) :
eno 2.4.1
eno ws 1.6.1
lunatic model 2.3.1

**Comment by AnneHuSKa** [comment]
![image](https://github.com/InseeFr/Eno/assets/71011059/4f38e886-2122-48d5-80f7-a5a950b45e9e)

Autre information :
Lunatic Model 2.3.2-rc4 : c'est ok
Lunatic Model 2.3.2-rc5 : c'est ok

**Comment by AnneHuSKa** [comment]
Eno version | 2.4.3-main
Eno WS 1.6.3-main 
Lunatic Model version | 2.3.2-master

ok

**Comment by nsenave** [comment]
Pour mémoire : le problème venait de Lunatic-Model (plus de détails : https://github.com/InseeFr/Lunatic-Model/pull/96 https://github.com/InseeFr/Lunatic-Model/pull/97 )
