### ISSUE TITLE
DDI 3.3 small adaptations

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#593]
Working on the Eno DDI application profile, we found that the existing generation produces 3.2 elements (replaced in 3.3):

- `d:SourceQuestion`
- `d:SourceVariable`

Those elements, found in `d:ProcessingInstructionScheme/d:GenerationInstruction`, are replaced respectively by:

- `d:InputQuestionReference`
- `d:InputVariableReference`

See:

![image](https://github.com/InseeFr/Eno/assets/1663283/43d8b01c-50aa-4af2-aecd-59e5e258998e)

Currently, those changes don't seem to have any impact on the Lunatic model generation.

For more information, see the [`GenerationInstruction` documentation](https://ddialliance.github.io/ddimodel-web/DDI-L-3.3/item-types/GenerationInstruction/).

**Comment by nsenave** [comment]
should be fixed thanks to @BulotF commit 1e3f4a751cf6f70cd9a212f4996bcf66ec0d64fd in #618

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Eno-WS/pull/124
