### ISSUE TITLE
Refactoring source-fixed.xsl of DDI

### ISSUE THREAD

**Issue by Mugiwara84** [InseeFr/Eno#61]
There might be something to do with :
- the multiple templates with enoddi:get-label mode and the creation of labels from QuestionText, ordinary Instruction, 'format' Instruction and 'tooltip' instruction.
- the multiple templates with lang-choice mode which are multiplied due the comlpexity described above

It might be impacted by issue #54. 
It might help if the labels on the DDI side were harmonized.
Maybe something better or simpler could be done on the produced xhtml.

**Comment by ORogel** [comment]
Done.
