### ISSUE TITLE
EnoV2 Pogues2DDI pour le suggester

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#610]

**Comment by laurentC35** [comment]
Waiting for ddi modeling
Only for EnoV2 because in enoV3 directy generate pogues2lunaticXML

**Comment by AnneHuSKa** [comment]
@nsenave : je ne comprends pas trop ?

**Comment by nsenave** [comment]
@AnneHuSKa si je comprends bien : modélisation DDI du suggester.

Implique d'implémenter la transformation Pogues vers DDI dans Eno Xml.

Pas un sujet pour l'instant pour Eno Java : la prochaine transformation sera "Pogues en entrée" (alors, Eno Java pourra faire Pogues vers Lunatic directement, "DDI en sortie" viendra plus tard). C'est la transformation DDI vers Lunatic qui est un sujet pour Eno Java cf. #494 

NB : la transformation DDI vers Lunatic pour suggester est faite dans Eno Xml (pas d'issue créée là dessus).

Le travail est fait, mais on attend d'avoir la possibilité de tester de bout en bout pour valider (InseeFr/Pogues-Back-Office#179 + charger les nomenclatures dans un orchestrateur dans un environnement de recette).
