### ISSUE TITLE
[Eno v3] Lunatic `"loopDependencies"`

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#611]
Lunatic loop components have a  `"loopDependencies"` property.

This property is not covered yet in Eno v3.

## Spec

- For "main"/"standalone" loops: it is the "binding dependencies" of "min" and "max" expression in the "lines" property.
- For linked loops: it is the "binding dependencies" of the "iterations" expression.

🗒️ For main loop, it may be only the "max" expression, to be confirmed.

- [ ] Verify use of this props in Lunatic

**Comment by laurentC35** [comment]
ToDo : Verify use of this props in Lunatic @laurentC35

**Comment by AnneHuSKa** [comment]
Globalement bien. Voir https://github.com/InseeFr/Eno/issues/772
