### ISSUE TITLE
[EnoV3] end point transformation vers fo

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#612]
End point fo /integration-business/ddi-2-fo
Integration of questionnaire according to params, metadata and specificTreatment. :
Renvoie 
Unknown error during generation : 415 UNSUPPORTED_MEDIA_TYPE "Content type 'text/xml' not supported for bodyType=org.springframework.web.multipart.MultipartFile"

**Comment by nsenave** [comment]
https://github.com/InseeFr/Eno/commit/dcf29add0b676c7801b43264fdfebe7049111ffc
