### ISSUE TITLE
[Eno v3] Mapping Date/Duration not always working

### ISSUE THREAD

**Issue by davdarras** [InseeFr/Eno#620]
Mapping Date/Duration objects work when there is a datedomaintype associated in the ddi corresponding objects.

But sometimes, there is no DateDomainType but a DateReferenceDomain associated to the objects in the DDI. 

We should take care of this second approach in Eno.

**Comment by AnneHuSKa** [comment]
@nsenave @BulotF que puis-je recetter sur ce sujet svp ? Le composant Date semble ok mais Durée n'existe pas encore
