### ISSUE TITLE
Consistency of the enoddi:get-codes-first-dimension getter

### ISSUE THREAD

**Issue by bibirico** [InseeFr/Eno#63]
The enoddi:get-codes-first-dimension getter doesn't return consistent result between Table and TableLoop driver.
In the first case it's a sequence of <l:Code/> that are returned, on the other it's a sequence of <Dummy/> elements (used only to render the number of lines).
In the ddi2fr implementation, the TableLoop driver never use this getter but still it's a bit confusing for new implementation.
This getter should return consistent results from both driver (in the ddi2fr implementation, a dummy sequence is enough as l:Code are never used through this getter, only the number of lines is used).

**Comment by ORogel** [comment]
Done.
