### ISSUE TITLE
[Eno v3] Null lines in tables

### ISSUE THREAD

**Issue by davdarras** [InseeFr/Eno#632]
When generating tables, Eno has some issues with body lines. In some cases, null body lines are added, and sometimes a IndexBoundException occurs

**Comment by AnneHuSKa** [comment]
Pas eu de nouveau cas mais impossible tester sur lk9tccqa  Unknown error during generation : Linked loop 'l5qrxyq8' is based on loop 'l5qrima7' that starts at sequence 'kz5bmih9'. This first question of the sequence is not a "simple" question.

**Comment by nsenave** [comment]
@AnneHuSKa merci pour le retour!

Première chose à constater... : #730 

Ici le problème : 

- la boucle `S2ALIER` a comme première question un tableau
- la règle Eno pour définir les occurrences d'une boucle liée est de donner à la boucle liée une formule VTL `count(<première variable de la boucle principale)`
- la boucle `S2LIEE` est basée sur `S2ALIER` => Eno voit que la première question de la boucle principale c'est pas une question à réponse simple, donc ne sait pas définir la formule du nombre d'occurrences pour la boucle liée => 💥 

➡️ Si je comprends bien, quand on a un tableau statique, on va utiliser la première variable de ce tableau pour générer la formule, exemple `count(TABPRENOML)`

**Comment by AnneHuSKa** [comment]
Merci pour les éclaircissements ! Discussion du 26/09  : cas totalement "surréaliste" donc on l'interdit (que ce soit un tab dynamique ou fixe)
