### ISSUE TITLE
[Eno V3] présence à tort de certains controles dans la version avec paramètre "controls":false

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#703]
En PJ, un DDI et le json généré avec https://enov3.demo.insee.io/webjars/swagger-ui/index.html#/Simple%20generation%20of%20questionnaire/generateLunaticJsonQuestionnaire
Présence à tort de controles de type : 
      "typeOfControl": "CONSISTENCY",
                    "criticality": "INFO",

[issue703.zip](https://github.com/InseeFr/Eno/files/12535182/issue703.zip)

J'ai l'impression que controls : false génère les controles et controls : true ne les génère pas ?

**Comment by nsenave** [comment]
même commentaire, paramètre "controls" : #704
