### ISSUE TITLE
[Eno V3] présence à tort de FILTER_RESULT dans la version avec paramètre "filterResult":false

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#704]
cf. fichiers dans [issue703](https://github.com/InseeFr/Eno/issues/703)

**Comment by nsenave** [comment]
Dans la version `3.9.0-SNAPSHOT` ils sont présents peu importe la valeur du paramètre "controls", ça sera corrigé à la prochaine livraison pour recette (cet aprem).
