### ISSUE TITLE
[Eno-V3] :  A typo: INPUTED instead of INPUTTED

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Eno#712]
There is a typo in the Lunatic Collected data possible field. It should be INPUTTED instead. I believe it's the right time to correct this before the management mode is released. 

Link issue : 
- https://github.com/InseeFr/Lunatic/issues/614
- https://github.com/InseeFr/Lunatic-Model/issues/112

**Comment by nsenave** [comment]
It has no impact in Eno v3, so it can be changed without any problem!

**Comment by nsenave** [comment]
Aucune modification côté Eno pour ce champ, le changement est fait côté Lunatic-Model.

Pas utilisé dans Lunatic donc pas d'impact sur le fonctionnement du questionnaire.

Mais en y réfléchissant il faut reporter ce changement sur la v2 de Lunatic-Model pour ne pas planter le batch extract data de Sabiane qui fait des conversions json/xml.
