### ISSUE TITLE
[Eno V3] génération impossible sur cas réel 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#713]
A l'épreuve des concepteurs : je n'arrive pas à générer ce cas.
Un souci de conception qu'Eno V3 refuse de gérer ?
[vpp_reinterro.zip](https://github.com/InseeFr/Eno/files/12587851/vpp_reinterro.zip)

=> li49zxju sur pogues EnoV3

**Comment by nsenave** [comment]
C'était une erreur de dev qui était passée entre les mailles du filet jusqu'ici...! Réglé avec #728
