### ISSUE TITLE
Addition of new transformations

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Eno#72]
Development of XMLPogues to DDI
Integration of  XMLPogues to DDI
Development of DDI to XMLPogues
Integration of  DDI to XMLPogues

**Comment by bwerquin** [comment]
New issue (#99 ) for : 
Development of XMLPogues to DDI
Integration of XMLPogues to DDI

**Comment by bibirico** [comment]
A XMLPogues2DDI v1 has been released on master.
