### ISSUE TITLE
[Eno V3] contenu de la page de fin

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#723]
Par un paramétrage dédié, on peut ajouter des pages de fin standardisés (zone de commentaires, temps de réponse).
Aujourd'hui si on positionne le paramètre à true, la génération échoue:  "Length type has not been set in Eno question class fr.insee.eno.core.model.question.TextQuestion[id=COMMENT-QUESTION, name=COMMENT_QE]"

https://github.com/InseeFr/Eno/tree/main/src/main/resources/xslt/post-processing/lunatic-xml/end-question par exemple
https://github.com/InseeFr/Eno/tree/main/src/main/resources/xslt/post-processing/lunatic-xml/begin-question

**Comment by nsenave** [comment]
@AnneHuSKa question pour la section "response time": on veut que les deux questions "heures" et "minutes" soient sur la même page? 

On doit pouvoir faire ça en utilisant le traitement spécifique de regroupement de question, mais on pourrait faire en sorte que ça soit intégré automatiquement pour cette séquence "response time".

**Comment by AnneHuSKa** [comment]
@nsenave : oui stp, il faut que les 2 questions Heures et Minutes soient sur la même page, sans passer par un TS (car on n'aura jamais le cas où les questions sont à séparer).
Use case : enquêtes entreprises, question systématique donc normalisée.

**Comment by AnneHuSKa** [comment]
Test du jour : des || en trop il me semble

**Comment by AnneHuSKa** [comment]
@nsenave : je n'arrive pas à générer pour les params Business car : "Unknown error during generation : The addition of the 'identification' section is not supported yet."
C'est lié ?

**Comment by nsenave** [comment]
(C'était en effet un petit truc, plus compliqué qu'il n'y paraît à gérer sans ajouter des cas particuliers un peu partout. J'ai finalement trouvé une manière correcte pour gérer correctement la numérotation Eno et la pagination Lunatic pour ces questions de fin.)

**Comment by AnneHuSKa** [comment]
merci @nsenave ca marche très bien
