### ISSUE TITLE
[Eno V3] absences controles cohérence dans une boucle liée 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#732]
Il me semble que les controles sur les variables des boucles liées ne fonctionnent pas / ne sont pas dans le json
Exemple en pj
[ControlesEnoV2.zip](https://github.com/InseeFr/Eno/files/12739749/ControlesEnoV2.zip)

remarque : le controle sur les variables de la boucle principale ne fonctionnent pas en EnoV2/Lunatic mais sont présents.

**Comment by nsenave** [comment]
Il y avait en effet un problème au niveau DDI -> Eno : la façon dont sont décrits les contrôles en DDI requiert un peu de code pour associer les contrôles avec les questions sur lesquelles ils s'appliquent. Un loupé dans ce morceau de code pour les boucles (et potentiellement aussi les filtres).

Corrigé et [testé](https://github.com/InseeFr/Eno/blob/d5236b0d539ce40e1afd081c9ea0d5187846d8b1/eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControlsTest.java#L20) avec le questionnaire dans le zip.

🗒️ _vérifier qu'on a bien les contrôles dans les composants qui se trouvent dans le périmètre d'un filtre_
