### ISSUE TITLE
[ddi2xforms][passage à Orbeon 2022] boucles de pages

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Eno#756]
Dans le cas des boucles de pages, Orbeon a perdu l'information qu'il ne doit pas les cacher lorsqu'il est sur d'autres pages.

Solution : rajouter dans la @relevant du xf:bind correspondant à la section la condition que la section courante doit être son identifiant.

**Comment by AnneHuSKa** [comment]
C'est bien dans la dernière version EnoV2 ? @nsenave @BulotF on peut fermer l'issue donc ?
