### ISSUE TITLE
[EnoV2] suppression dans la génération CAPI CATI d'un PreProcessing > ddi-markdownToXhtml

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#758]
Supprimer du pipeline       <PreProcessing>ddi-markdownToXhtml</PreProcessing> pour génération CAPI CATI

**Comment by bwerquin** [comment]
delete here : https://github.com/InseeFr/Eno-WS/blob/main/src/main/resources/params/lunatic-xml/capi/household.xml#L9

**Comment by AnneHuSKa** [comment]
passage à EnoV3 donc devenu sans objet
