### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Eno#77]

**Comment by FranckCo** [comment]
Includes architecture schema, process description, data model

**Comment by manuelLandreau** [comment]
Up! (Eno comes packaged in a REST web service using Eno-WS and a Docker image.)

Hello, what would be the process to run it through docker, i saw a dockerfile in the eno-ws repository but it doesn't seems to be complete. Can I have more precision about it, thanks !

**Comment by nsenave** [comment]
@manuelLandreau Just added a section for the docker image in [Eno-WS readme](https://github.com/InseeFr/Eno-WS/blob/main/README.md#from-docker-image)

InseeFr/Eno-WS@be497466c10e5afe2d492bdaaf6de8023fb5e126
