### ISSUE TITLE
[EnoV3] isoEnoV2 - affichage page blanche quand dernière question filtrée 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#771]
Comportement isofonctionnel EnoV2 donc à ne pas traiter pour passage en prod
Exemple un questionnaire avec 2 questions
Q1 filtre Q2
Si Q2 est masquée alors affichage d'une page blanche, navigable et passage question de fin.
 
[json-derniereQuestionFiltree.zip](https://github.com/InseeFr/Eno/files/13165766/json-derniereQuestionFiltree.zip)

**Comment by JulienCarmona** [comment]
Sera documenté ici 
- https://github.com/InseeFr/Bowie/issues/112
