### ISSUE TITLE
[Eno V3] génération de tableaux dynamiques 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#783]
https://github.com/InseeFr/Lunatic/issues/409

Produire le json correspondant à ce composant

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Eno/issues/819

**Comment by nsenave** [comment]
valider s'il faut bien mettre `"headers"`

**Comment by AnneHuSKa** [comment]
@nsenave j'ai tenté de générer et de vérifier dans le storybook 2.7 mais ca ne semble pas marcher. On en parle jeudi

**Comment by AnneHuSKa** [comment]
@nsenave : voici les json EnoXML et EnoJava. en XML, le tab dynamique s'affiche mais en Java on a une page blanche (testé en Lunatic)
[tabDynEnoxmletJava.zip](https://github.com/InseeFr/Eno/files/13916517/tabDynEnoxmletJava.zip)

**Comment by AnneHuSKa** [comment]
@nsenave : la cible pour les tableaux dynamiques avec controle est ici :  
Voici le rendu actuel enoV3, le DDI et un json POgues (lrf3chy8 en recette) : 
[json_Pogues_tabdyn_filiere.zip](https://github.com/InseeFr/Eno/files/14065229/json_Pogues_tabdyn_filiere.zip)
[ddi_tabdyn_filiere.zip](https://github.com/InseeFr/Eno/files/14065230/ddi_tabdyn_filiere.zip)
[Tab_dynEnoJava_ko.zip](https://github.com/InseeFr/Eno/files/14065231/Tab_dynEnoJava_ko.zip)
[tableaux-dynamiques-dans-la-filiere-avec-controles.zip](https://github.com/InseeFr/Eno/files/14065232/tableaux-dynamiques-dans-la-filiere-avec-controles.zip)

Voir  la fin de l'issue https://github.com/InseeFr/Lunatic/issues/409

**Comment by AnneHuSKa** [comment]
![image](https://github.com/InseeFr/Eno/assets/71011059/9599b1ca-59e9-46e6-a682-4c3eb5261ff7)
Toujours un affichage de page blanche.

Je remets la cible et j'ajoute ce qui est produit aujourd'hui 
[tableaux-dynamiques-dans-la-filiere-avec-controles.zip](https://github.com/InseeFr/Eno/files/14207675/tableaux-dynamiques-dans-la-filiere-avec-controles.zip)
[json_tabdyn_Eno3171.zip](https://github.com/InseeFr/Eno/files/14207690/json_tabdyn_Eno3171.zip)

**Comment by nsenave** [comment]
Le problème n'est pas au niveau des `"bindingDependencies"` mais au niveau des values : il faut impérativement `[null]` pour les tableaux dynamiques et pas `[]` comme pour les variables de boucle par exemple.

À voir s'il y a une raison côté Lunatic ou si ça relève d'un défaut d'implémentation.

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/issues/874
