### ISSUE TITLE
[Eno V3] générer le composant Durée (DDI2Lunatic)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#787]
Deux formats Durée créés en Lunatic (les deux premiers) et qui sont décrits dans POgues (et en modélisation DDI) : 
![image](https://github.com/InseeFr/Eno/assets/71011059/a5e24ca2-bf03-47d3-9f9d-292f3e01585b)

- https://github.com/InseeFr/Lunatic/issues/258 
- composant https://inseefr.github.io/Lunatic/storybook-2.7/?path=/story/components-duration--date-duration

Le DDI initial en PJ
[DDI_issue787.zip](https://github.com/InseeFr/Eno/files/13917735/DDI_issue787.zip)

 
=> adapter DDI2unatic

**Comment by nsenave** [comment]
Je mets en stand-by pour traiter ce sujet après les issues "critiques"

**Comment by nsenave** [comment]
Génération du composant `Duration` implémentée, ce qu'il reste à faire : 

- définition des propriété `"min"`/`"max"` Dans Lunatic / Lunatic-Model (à l'instar du Datepicker/InputNumber)
- génération des contrôles de format dans Eno
