### ISSUE TITLE
[Eno V2] Fix to breaking changes in Lunatic Pairwise component

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#795]
Need to adapt to [this changes](https://github.com/InseeFr/Lunatic/issues/792#issuecomment-1819583120).

**Comment by nsenave** [comment]
In Eno v3:

- [x] `"VTL"` type in `"xAxisIterations"` and `"yAxisIterations"` labels [code](https://github.com/InseeFr/Eno/blob/95c7c1d9f4a5c57221a96eeb45bc5d86631e07df/eno-core/src/main/java/fr/insee/eno/core/model/question/PairwiseQuestion.java#L50) / [test](https://github.com/InseeFr/Eno/blob/95c7c1d9f4a5c57221a96eeb45bc5d86631e07df/eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/PairwiseQuestionTest.java)
- [ ] no `"xAxis <> yAxis"` condition filter
- [x] quotes arround the question label [code](https://github.com/InseeFr/Eno/blob/95c7c1d9f4a5c57221a96eeb45bc5d86631e07df/eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInLabels.java#L58)

**Comment by AnneHuSKa** [comment]
Différents sujets :
- fait-on dans EnoV2 ? oui si on veut que Queen LunaticV2.7 soit opérationnelle (@BulotF @nsenave à discuter)
- fait-on dans EnoV3 : fait et à recetter
[testSuggesterStromaeSansXaxis.zip](https://github.com/InseeFr/Eno/files/13530218/testSuggesterStromaeSansXaxis.zip)
 @AnneHuSKa 

Impacts  : 
- dans Queen Lunaticv2.7 : à valider
- dans StromaeV2 (version Lunatic 2.4.9) : version corrigée fonctionnelle (cf. json ci joint, généré EnoV2, corrigé à la main et recetté Stromae 2.4.13)

**Comment by AnneHuSKa** [comment]
@BulotF va regarder en local

**Comment by AnneHuSKa** [comment]
Eno 2.7.0
