### ISSUE TITLE
Endpoint - tentative de mise à plat et bugs

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#826]
https://codimd.dev.kube.insee.fr/ltl3KJ6fRESWWBFg-QJp2A?edit

**Comment by AnneHuSKa** [comment]
Il faudra bien recetter tous les  endpoints proposés car à ce jour certains (V3-business-cawi par exemple) échouent lorsqu'on met un TS

**Comment by nsenave** [comment]
> Il faudra bien recetter tous les endpoints proposés car à ce jour certains (V3-business-cawi par exemple) échouent lorsqu'on met un TS

Je déplace l'aspect bug dans une issue séparée #851
