### ISSUE TITLE
[Eno V3] questionnaire qui pose un souci de génération

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#827]
lk9kc2y9 sur pogues-enoV3
J'ai des "Duplicate ID "lg2eaajg-SI" found in given DDI." mais je ne sais pas d'où ca vient ?

**Comment by BulotF** [comment]
Un identifiant qui termine par -SI est un StatementItem : il s'agit des déclarations associées à une question dans Pogues, mais pas dans DDI. De mémoire, les déclarations situées AVANT le libellé de question.

Je dirais qu'il a pu y avoir composition à partir de questionnaires dupliqués. Une déclaration était présente dans les deux versions du questionnaire, avec le même identifiant. La gestion de doublons des identifiants n'a pas été faite sur les déclarations.

Autre possibilité : un peu pareil, mais sans composition de questionnaires. 2 questions partagent la même déclaration "pré-question", sauf que dans DDI, l'identifiant de cette déclaration, sortie de sa question, n'inclut pas l'identifiant de la question (les 2 identifiants sont collés, d'habitude), ce qui aurait levé le doublon.

Solutions (au choix) : 
- modifier l'un des deux identifiants dans le json Pogues
- supprimer, puis recréer l'une des deux déclarations dans l'IHM Pogues
- gérer le cas dans Pogues back-office (nettement plus cher)
