### ISSUE TITLE
[EnoV3] Manque de certains BindingDependencies suite passge Lunatic 2.7

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#829]
https://github.com/InseeFr/Lunatic/issues/832

Un souci sur le calcul de certaines variables utilisant le concept de LIENS (quand on collecte les liens deux à deux - PAIRWISE).
(exemple tiré d'un cas usage TCM)
Le json et des data associées en pj

Exemple 
en 2.7 : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/58b7f068-1054-46dd-bee2-f808bbedfe18)
en 2.6 :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/42565b2b-114e-4e35-9551-932356c67642)

Jonathan a remarqué un truc étrange dans le JSON car s'attendait à ce que T_NBHAB soit en bindingDependencies car il est utilisé dans l'expression. En corrigeant cette erreur le formulaire fonctionne comme attendu.

        {
            "variableType": "CALCULATED",
            "bindingDependencies": ["LIENS"],
            "expression": {
                "type": "VTL",
                "value": "if T_NBHAB > 3 then ( if (\"1\" in LIENS) and (\"3\" ....."
            },
            "name": "T_C_ENF_I",
            "inFilter": "true",
            "shapeFrom": "T_PRENOM"
        },

 
Il faut corriger coté eno car si on fait coté Lunatic, donc si on ignore les bindingDependencies (on les recalcule depuis l'expression (ce qui était fait dans la 2.6), cela implique un surcout de performance au chargement des variables).

**Comment by nsenave** [comment]
Je n'arrive pas à reproduire le bug

Le problème existe à la fois dans Eno Xml et dans Eno Java : j'ai le même résultat en génération le json Lunatic à partir du DDI "lq0qm697" depuis Eno Xml ou Eno Java.
Je me demande si le problème ne si situe pas au niveau de la transformation Pogues -> DDI (?)

[form-lq0qm697.zip](https://github.com/InseeFr/Eno/files/13830308/form-lq0qm697.zip)

Dans ce DDI il y a une variable calculée qui utilise plusieurs variables dont la variable des liens deux à deux, les binding dependencies sont ok : 

[ddi-calculated-pairwise.zip](https://github.com/InseeFr/Eno/files/13830328/ddi-calculated-pairwise.zip)

**Comment by AnneHuSKa** [comment]
@BulotF @nsenave : en fait, le souci vient de la nouvelle version Lunatic (2.7) donc à voir comment on corrige

**Comment by AnneHuSKa** [comment]
@nsenave : tu sais si c'est cher stp ? On a un besoin SRCV pour fin janvier ? merci

**Comment by nsenave** [comment]
PEBKAC error: il manque des `$` autour de certaines variables dans les formules saisies via l'UI Pogues. 

(L'absence de ces délimiteurs fait que Pogues n'identifie pas ces variables dans les formules, donc elles n'apparaissent pas dans les `InParameter` en DDI, et donc pas dans les `bindingDependencies` dans Lunatic)
