### ISSUE TITLE
[Eno v3] Specific treatment fails on certain endpoints

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#851]
> Il faudra bien recetter tous les  endpoints proposés car à ce jour certains (V3-business-cawi par exemple) échouent lorsqu'on met un TS

_Originally posted by @AnneHuSKa in https://github.com/InseeFr/Eno/issues/826#issuecomment-1867388376_

**Comment by AnneHuSKa** [comment]
ok
