### ISSUE TITLE
[EnoV3] endpoints en erreur

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#852]
Début de recette https://api-generation-questionnaires-recette2.etc.. : 

- [ ] POST [/questionnaire/ddi-2-fo] : il me semble qu'avant on avait un pipeline business ? J'ai testé avec un questionnaire ménages et un entreprise et j'ai un Eno parameters error: No mode defined in Eno parameters file given. On en parle jeudi ?
- [ ] POST [/questionnaire/ddi-2-xforms] : : il me semble qu'avant on avait un pipeline business ? J'ai testé avec un questionnaire entreprise et j'ai un Eno parameters error: No mode defined in Eno parameters file given. 
-
- [ ] POST [/questionnaire/{context}/xforms] : Unknown error during generation: SSLTube(SocketTube(5)) stream=1 [reactor-http-epoll-6] Too few bytes returned by the publisher (0/984670)

**Comment by nsenave** [comment]
Pour le deuxième point :

> POST [/questionnaire/ddi-2-xforms] : : il me semble qu'avant on avait un pipeline business ? J'ai testé avec un questionnaire entreprise et j'ai un Eno parameters error: No mode defined in Eno parameters file given.

C'est volontaire, j'ai ajouté des contrôles si le fichier de paramètres ne contient pas le mode de collecte. Précédemment dans le code à cet endroit : 1/ lecture du fichier de paramètres 2/ si le mode est null, alors le mode = business

Je me suis dis que ça pourrait être une source d'erreur bien plus tard : on met un mauvais fichier de paramètres sans s'en apercevoir, le questionnaire se génère, et plus loin dans le processus on constate des problèmes qu'on a du mal à expliquer...

Normalement avec un fichier de paramètres généré avec `/parameters/xml/BUSINESS/XFORMS` avec l'option "Mode" à `CAWI` ou `PROCESS` ça devrait fonctionner.

**Comment by nsenave** [comment]
(Ça devrait être analogue pour le premier point)

**Comment by nsenave** [comment]
@AnneHuSKa Le troisième point est corrigé dans la version `3.15.3` 

Tu me diras si c'est ok pour les deux autres

**Comment by nsenave** [comment]
> @nsenave : ok vu et compris. J'ai réussi en changeant les params. En revanche le nom du fichier en sortie n'est pas bon - on dirait qu'il ne lit pas le fichiers des metadata ? Pour xforms il s'appelle test-2020-x00.zip au lieu de par exemple tic 2023-a00.zip

Le nom du fichier en sortie vient du fichier de paramètres, pas celui des metadata, non ?
