### ISSUE TITLE
Bad parsing of regexes containing `[...](...)`

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#854]
I want to have a declaration that display an integer with a thousand separator, the easiest way to do that is to combine the VTL function `replace` with a regex, the code is:

```
"Vous avez saisi : " || 
replace(
    cast($NBR$, integer), 
    "[0-9](?=(?:[0-9]{3})+(?![0-9]))", "$& "
)
```

It is working in pure TrevasJS (it can be check at https://inseefr.github.io/Trevas-TS/storybook/storybook-static/?path=/story/interpretor-string--replace).

In Bowie, it doesn't:

![image](https://github.com/InseeFr/Eno/assets/1663283/2e64fbc6-4552-4ab4-b088-2d8d5e6e46d0)

When i look at the generated JSON for Lunatic, i see:

```json
"declarations": [
	{
		"declarationType": "HELP",
		"id": "lraevesb-lraf953q",
		"label": {
			"type": "VTL|MD",
			"value": "\"Vous avez saisi : \" || replace( cast(NBR, integer), ’[0-9](?=(?:[0-9]{3})+(?![0-9]))’, \"$& \" )"
		},
		"position": "AFTER_QUESTION_TEXT"
	}
]
```

It seems there is a transformation of the regex, see the sort of backticks in `’[0-9](?=(?:[0-9]{3})+(?![0-9]))’`

My two cents: the `[...](...)` syntax is interpreted as a markdown links as we can see in the screenshot above.

**Comment by JulienCarmona** [comment]
Ca fonctionne si on change un peu la formule et qu'on cast en string plutôt
```
"Vous avez saisi : " || 
replace(
    cast(NBR, string),
    "[0-9](?=(?:[0-9]{3})+(?![0-9]))", "$& "
)
```
https://inseefr.github.io/Trevas-TS/storybook/storybook-static/?path=/story/interpretor-string--replace
![{1E096023-E935-4B84-B4A9-51AFCA06FCFE}](https://github.com/user-attachments/assets/be016521-2672-4ad4-9bb1-80dba99c252b)

**Comment by AnneHuSKa** [comment]
Voir si on documente @JulienCarmona @lailabent
