### ISSUE TITLE
EnoV3 - génération SRCV

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#865]
Unknown error during generation: SpEL mapping expression defined on property 'type', for format DDI, in class fr.insee.eno.core.model.sequence.ItemReference, failed on object ReferenceTypeImpl

[ddi_srcv.zip](https://github.com/InseeFr/Eno/files/13965243/ddi_srcv.zip)

**Comment by AnneHuSKa** [comment]
Souci lors de la composition (module invisible)

**Comment by nsenave** [comment]
Pour mémoire : l'erreur venait de Pogues : 

1. une erreur au niveau du front liée à la composition : une référence à un questionnaire externe pouvait apparaître plusieurs fois dans le corps du questionnaire, mais elle n'était bien présente qu'une fois dans la liste des références (`"childQuestionnaireRef"` dans le json Pogues)
2. Conséquence côté Pogues backend : la référence en question n’apparaît qu'une seule fois dans la liste des questionnaires référencés, donc une des deux était remplacée, l'autre était laissée telle quelle (référence vers un questionnaire externe sans contenu).
3. Dans la transformation Pogues vers DDI faite par Eno Xml : la référence laissée telle quelle devient une séquence, mais n'a pas l'information DDI "`TypeOfSequence`".
4. Conséquence côté Eno Java dans la transformation DDI vers Lunatic : tentative de convertir le "type of sequence" DDI (pour savoir s'il s'agit d'une séquence ou d'une sous-séquence), mais cette propriété est `null` pour cette référence => l'erreur mentionée plus haut

> Unknown error during generation: SpEL mapping expression defined on property 'type', for format DDI, in class fr.insee.eno.core.model.sequence.ItemReference, failed on object ReferenceTypeImpl

Ça a été corrigé dans Pogues (front) depuis.

NB : un contrôle en plus côté Pogues-Back-Office (vérifier qu'il n'y a pas de doublons de questionnaires externes) ne ferait pas de mal.
