### ISSUE TITLE
EnoV3 - transformation des identifiants techniques en variables métier au delà de 10 variables

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#872]
Lorsqu'une formule fait intervenir plus de 10 variables, la formule n'est pas bien "traduite"
Exemple TIC :

<r:CommandContent>(nvl(lnvl0f2y-IP-1, false) or nvl(lnvl0f2y-IP-2, false) or nvl(lnvl0f2y-IP-3, false) or nvl(lnvl0f2y-IP-4, " ") = "1" or nvl(lnvl0f2y-IP-5, " ")="1" or nvl(lnvl0f2y-IP-6, " ") = "1" or nvl(lnvl0f2y-IP-7 , " ") ="1" or nvl(lnvl0f2y-IP-8, false) or nvl(lnvl0f2y-IP-9, false) or nvl(lnvl0f2y-IP-10, false) )</r:CommandContent>

=>"value": "((nvl(RESIDENCE, \"9\") = \"1\" or nvl(RESIDENCE, \"9\")=\"9\")) and (PRESAKO = \"1\") and ((NUSEWEB = \"1\" or NUSEWEB =\"2\")) and ((nvl(ADMX1, false) or nvl(ADMX2, false) or nvl(ADMX3, false) or nvl(IMPADM, \" \") = \"1\" or nvl(RDVADM, \" \")=\"1\" or nvl(MESADM, \" \") = \"1\" or nvl(DECLADM , \" \") =\"1\" or nvl(RAIADMX1, false) or nvl(RAIADMX2, false) or nvl(**ADMX10**, false) ))",
[ddi_tic.zip](https://github.com/InseeFr/Eno/files/14008274/ddi_tic.zip)

**Comment by AnneHuSKa** [comment]
@nsenave @BulotF : j'ai le même souci sur une variable plus complexe encore ; PBIOTX  12modalités.
Le DDI décrit un filtre 
<r:CommandContent> (nvl(lnvu06vi-IP-1, false) or nvl(lnvu06vi-IP-2, false) or nvl(lnvu06vi-IP-3, false) or nvl(lnvu06vi-IP-4, false) or nvl(lnvu06vi-IP-5, false)  or nvl(lnvu06vi-IP-6, false) or nvl(lnvu06vi-IP-7, false) or nvl(lnvu06vi-IP-8, false) or nvl(lnvu06vi-IP-9, false) or nvl(lnvu06vi-IP-10, false)  or or nvl(lnvu06vi-IP-11, false))</r:CommandContent>

alors que le json renvoie 

"value": "((nvl(RESIDENCE, \"9\") = \"1\" or nvl(RESIDENCE, \"9\")=\"9\")) and (PRESAKO = \"1\") and (NUSEWEB = \"1\") and 
				((nvl(HOMEIOTX1, false) or nvl(HOMEIOTX2, false) or nvl(HOMEIOTX3, false) or nvl(HOMEIOTX4, false) or 
				 nvl(TVIOTX1, false) or nvl(TVIOTX2, false) or nvl(TVIOTX3, false) 
				 nvl(AUTIOTX1, false) or nvl(AUTIOTX2, false) or nvl(AUTIOTX3, false) or 
			  or nvl(AUTIOTX4, false)))"

Je vais corriger demain la faute sur le "double or" dans la description Pogues mais il y  a peut-être un sujet Eno non ?

**Comment by AnneHuSKa** [comment]
Pas de sujet, merci @BulotF ! Un double or qui pose souci. Signalé au concepteur. 
3.15.9

**Comment by nsenave** [comment]
NB : corrigé par #873
