### ISSUE TITLE
Variable _missing pour les LIENS

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#875]
Aujourd'hui en EnoJava, on se retrouve avec 
                   "missingResponse": {"name": "fr.insee.lunatic.model.flat.ResponseType@5736ab07_MISSING"},
ce qui semble étrange ? On attend LIENS_MISSING ?

Dans le data, on a par exemple 

```json
"COLLECTED": {
      "fr.insee.lunatic.model.flat.ResponseType@bb6d9e4_MISSING": {},
      "LIENS": {
        "COLLECTED": [
          [
            null,
            "2",
            "11"
          ],
          [
            "3",
            null,
            "10"
          ],
          [
            "13",
            "9",
            null
          ]
        ]
      },
```

**Comment by nsenave** [comment]
NB : cette issue fait suite à :

- #842

Probablement un loupé quelque part (du style objet response inséré au lieu de l'attribut "name" de l'objet response).
