### ISSUE TITLE
Lunatic "Missing" variables for iterated variables doesn't have the `"value"` property

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#891]
Lunatic "MISSING" variables that correspond to variables that are defined in a iterated object (loop/dynamic table/dynamic table) don't have their `"value"` property initialized.

Variables that are collected in a loop, dynamic table or pairwise question must have an initialized `"value"` array (otherwise data collection fails in Lunatic).

in the loop/dynamic table case:

```json
{
    "values": {
      "PREVIOUS": [],
      "COLLECTED": [],
      "FORCED": [],
      "EDITED": [],
      "INPUTED": []
}
```

in the pairwise case:
 
```json
{
    "values": {
      "PREVIOUS": [[]],
      "COLLECTED": [[]],
      "FORCED": [[]],
      "EDITED": [[]],
      "INPUTED": [[]]
}
```

**Comment by AnneHuSKa** [comment]
{
			"variableType": "COLLECTED",
			"values": {
				"COLLECTED": [],
				"EDITED": [],
				"INPUTED": [],
				"FORCED": [],
				"PREVIOUS": []
			},
			"name": "COMBIEND"
		},
		{
			"variableType": "COLLECTED",
			"values": {
				"COLLECTED": [
					[]
				],
				"EDITED": [
					[]
				],
				"INPUTED": [
					[]
				],
				"FORCED": [
					[]
				],
				"PREVIOUS": [
					[]
				]
			},
			"name": "LIENS"
		},
