### ISSUE TITLE
Lunatic "Missing" variables should be defined for the loop inner components

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Eno#893]
In the current implementation, Lunatic non-paginated loops (i.e. loops where all components are displayed on the same page in Lunatic) have a single missing response.

A regression at some point in Lunatic has broken this functionnality in that case.

Two options are possible:

- fix Lunatic to reproduce this behavior
- update the missing feature in Eno in that case to that there would be one missing response for each component in the loop

Note: If the latter is done in Eno, no change is required in Lunatic to make it work (seen with @grafikart )

---

Disscussed with @romaintailhurat: ok to do the second option.

**Comment by AnneHuSKa** [comment]
Ok en 3.17
