### ISSUE TITLE
Non affichage de déclarations avant (Statement, StatementItem) dans les sous séquences filtrées

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#912]
Un concepteur a décrit des déclarations avant (StatementItem). La visualisation de la question seule ne pose aucun souci.

La visualisation du questionnaire complet en revanche n'affiche pas ces déclarations avant.

Exemple :
Question "Manger" (lsj5606z s'affiche mais lsa7p1th ne s'affiche pas)
[Info_EHIS.zip](https://github.com/InseeFr/Eno/files/14343029/Info_EHIS.zip)

**Comment by AnneHuSKa** [comment]
=> les StatementItem des questions filtrées ne figurent pas dans le JsonLunatic

**Comment by nsenave** [comment]
La modélisation DDI des StatementItem est assez tricky, en effet le code Eno java ne gère pas le cas où une séquence/question est dans la portée d'un filtre pour ces déclarations. C'est probablement également le cas pour le cas d'une séquence dans une boucle (les déclaration "avant question" des questions à l'intérieur ne sont pas insérées).

Je corrige ça

**Comment by AnneHuSKa** [comment]
3.18.5 ok
