### ISSUE TITLE
Autres Préciser - génération conforme à issue Lunatic 204

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#919]
- https://github.com/InseeFr/Lunatic/issues/204

DDI (QCMETAUTRE3CL : variable à afficher si QCMETAUTRE = "3")
[ddi_AutresPreciser.zip](https://github.com/InseeFr/Eno/files/14416124/ddi_AutresPreciser.zip)

Permettra de clore:

- https://github.com/InseeFr/Eno/issues/860

**Comment by nsenave** [comment]
Point d'étape : fonctionnalité "Autre précisez" implémentée dans DDI -> Lunatic pour :

- les `Radio`, `CheckboxOne`
- les `CheckboxGroup`

Cas non couverts : 

- les `Dropdown`
- composant de réponse à choix unique (Radio / Dropdown / CheckboxGroup) dans une cellule de tableau

@AnneHuSKa on peut fermer cette-issue et en ouvrir de nouvelles plus tard si on veut traiter ces cas là.
