### ISSUE TITLE
Controles dans les tableaux dynamiques

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#920]
https://github.com/InseeFr/Eno/issues/783
A priori les contrôles ne fonctionnent pas comme préconisé par le json cible

[ddi_tabdyn_filiere.zip](https://github.com/InseeFr/Eno/files/14422216/ddi_tabdyn_filiere.zip)
Cible ok (hormis les types et formats des controles) : [tableaux-dynamiques-dans-la-filiere-avec-controles.zip](https://github.com/InseeFr/Eno/files/14422217/tableaux-dynamiques-dans-la-filiere-avec-controles.zip)
Version actuelle ko : [Json_Controles_tabDyn_ko.zip](https://github.com/InseeFr/Eno/files/14422637/Json_Controles_tabDyn_ko.zip)

**Comment by BulotF** [comment]
Au niveau des contrôles de tableaux dynamiques, faute de meilleur emplacement, l'information des contrôles de lignes de tableaux dynamiques sera portée par le champ d:TypeOfComputationItem

On avait jusqu'à présent, 3 valeurs possibles : 
```
<d:TypeOfComputationItem controlledVocabularyID="INSEE-TOCI-CL-1">informational</d:TypeOfComputationItem>
<d:TypeOfComputationItem controlledVocabularyID="INSEE-TOCI-CL-2">warning</d:TypeOfComputationItem>
<d:TypeOfComputationItem controlledVocabularyID="INSEE-TOCI-CL-3">stumblingblock</d:TypeOfComputationItem>
```

On rajouterait 3 modalités : 
```
<d:TypeOfComputationItem controlledVocabularyID="INSEE-TOCI-CL-11">line-informational</d:TypeOfComputationItem>
<d:TypeOfComputationItem controlledVocabularyID="INSEE-TOCI-CL-12">line-warning</d:TypeOfComputationItem>
<d:TypeOfComputationItem controlledVocabularyID="INSEE-TOCI-CL-13">line-stumblingblock</d:TypeOfComputationItem>
```

Compte tenu de l'issue #942 les modalités se traduiraient ainsi en Lunatic : 
- informational: 
  - "criticality": "INFO",
- warning: 
  - "criticality": "WARN",
- stumblingblock: 
  - "criticality": "ERROR",
- line-informational: 
  - "type": "ROW",
  - "criticality": "INFO",
- line-warning: 
  - "type": "ROW",
  - "criticality": "WARN",
- line-stumblingblock: 
  - "type": "ROW",
  - "criticality": "ERROR",
