### ISSUE TITLE
Support not collected variables substitution

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#932]
Currently, when unchecked, we add a NoDataByDefinition in DDi (see https://github.com/InseeFr/Eno/issues/596). This is supported by Eno Java.

We would like now to support a substitution by a value or a variable, see See https://github.com/InseeFr/Pogues/issues/745

**Comment by nsenave** [comment]
@AnneHuSKa Oui ça fait partie de :

- #1029
