### ISSUE TITLE
Controles - modification de criticality

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#942]
Dans la filière, on peut décrire dans Pogues trois types de controles : INFO (information), WARN (avertissement) et ERROR (erreur). Dans Lunatic, aujourd'hui, ils sont traduits en  "criticality": "INFO".
Or suite aux évolutions pour Stromae V3, les affichages et visuels des contrôles ont été revus. 

* Non bloquant avec error.typeOfControl === 'CONSISTENCY'
criticality :
     - ERROR ou WARN -> Rouge
     - INFO -> Vert

* Bloquant : error.typeOfControl === 'FORMAT' || error.criticality === 'ERROR'

Afin de rendre cohérentes la logique des contrôles dans Pogues et celle dans Lunatic, il faut pouvoir distinguer les différentes erreurs : on propose donc de modifier la transfo DDI2Lunatic afin que les 3 contrôles se traduisent en :
- [ ] Pogues "criticity": "INFO"   //  DDI : TypeOfComputationItem : informational          // Lunatic  "criticality": "INFO"  (inchangé)
- [ ] Pogues "criticity": "WARN"  //  DDI : TypeOfComputationItem : warning                // Lunatic  "criticality": "WARN" (modifié)
- [ ] Pogues "criticity": "ERROR" //  DDI : TypeOfComputationItem : stumblingblock         // Lunatic  "criticality": "ERROR" (modifié)

**Comment by AnneHuSKa** [comment]
[ddi942.zip](https://github.com/InseeFr/Eno/files/14745042/ddi942.zip)

**Comment by AnneHuSKa** [comment]
@nsenave : en même temps que controles tableaux coté @romaintailhurat si possible stp ?

**Comment by nsenave** [comment]
https://github.com/InseeFr/Eno/commit/0622ec5aee8102769c9de077ce4b065332346990
