### ISSUE TITLE
Traitement spécifique regroupement - limite à 2 questions à tort ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#951]
Le traitement spécifique permettant de regrouper plusieurs questions par page est limité à 2 réponses ?
Si oui, coût de ne pas mette de limite ? (ou une plus grande ?)

**Comment by nsenave** [comment]
Non pas de limitation sur le nombre de questions qui peuvent être regroupées  (la seule contrainte c'est un minimum de 2 par regroupement).

**Comment by AnneHuSKa** [comment]
Je suis tombée sur l'exception (les QCM qu'on ne peut pas regrouper), donc merci pour ton retour, c'est parfait comme c'est !
