### ISSUE TITLE
`Question` Component, generated by default according to modelisation of Lunatic-DSFR story

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Eno#957]
Story: https://inseefr.github.io/Lunatic-DSFR/storybook/?path=/docs/components-question--documentation

**Comment by AnneHuSKa** [comment]
Retour sur 3.20.0 : 
- le seul label spécifiable aujourd'hui dans Pogues devient celui du composant Question - on ne permet donc pas à court terme plusieurs champs de réponse / Input dans le composant Question
![image](https://github.com/InseeFr/Eno/assets/71011059/fa580af0-a0a2-43d0-98ce-8c05057315ff)
- avec DSFR = true, plus de "declarationType": "STATEMENT" (qui sont aujourd'hui générées pour les BEFORE_QUESTION_TEXT) : remplacer par "declarationType": "HELP"
-

**Comment by nsenave** [comment]
@AnneHuSKa les changements que tu décris sont faits dans la 3.20.1
