### ISSUE TITLE
Calculated variables: new attribute: `variableDimension` = 0 / 1 / 2

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Eno#959]
For `CALCULATED` & `EXTERNAL` variables

**Comment by nsenave** [comment]
@AnneHuSKa c'est une issue de nature technique pour des simplifications côté Lunatic, à vérifier : 

- les collectées ont toujours `"values"`, avec des `null` pour le niveau questionnaire `[]` pour les variables de boucle, `[[]]` pour le liens deux à deux
- idem pour les externes avec `"value"`
- Tous les types de variables ont une `"dimension"` égale à `0` (niveau questionnaire), `1` (niveau boucle ou tableau dynamique), `2` (liens deux à deux)

NB : par opportunisme j'ai ajouté un `"iterationReference"` qui renvoie à la boucle/tableau dynamique/pairwise auquel est lié la variable (peut être utile à des fins de debug et pourrait simplifier des traitements dans Eno/Lunatic/autres applis qui utilisent le questionnaire Lunatic).

**Comment by AnneHuSKa** [comment]
ok (vérification génération CAWi et CAPI)
