### ISSUE TITLE
Modification params arrowCharInQuestions pour le mode CAWI

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#990]
Dans la génération DDI2Lunatic, modifier "arrowCharInQuestions" pour le mode CAWI :

- [ ]  "arrowCharInQuestions" = false pour Default
- [ ]  "arrowCharInQuestions" = false pour Business

Celui pour Household est juste

**Comment by nsenave** [comment]
`3.21.1-SNAPSHOT`
