### ISSUE TITLE
Description par défaut dans les InputNumber

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Eno#992]
Afin de répondre aux préconisations DSFR (afficher la manière de remplir un InputNumber) et en attendant une modélisation des "Description", on propose de générer une Description par défaut pour les composants InputNumber

**Proposition de Description**  : 
"Format attendu : un nombre " || (si unité non vide alors "en unité" sinon "")   ||    (si borne min >=0 et  borne max >=0 alors "entre  borne min et borne max" sinon ""

Exemples : 
Format attendu : un nombre en € entre 0.0  et 10.0
Format attendu : un nombre entre 0 et 100
Format attendu : un nombre en  k€ entre 20 et 1000

**Comment by romaintailhurat** [comment]
OK with Eno 3.21.5

**Comment by romaintailhurat** [comment]
Not so ok. With a minimum that is a negative number we get an error:

![image](https://github.com/InseeFr/Eno/assets/1663283/3fe46dcf-dae3-460d-b2fc-3bdf9ef31151)
